/***** Penn World Tables 6.0 and 6.1 codes *****/

program k_pwt6n
version 8.2

replace NAMES_STD = "Algeria" if NAMES_STD == "44"
replace NAMES_STD = "Albania" if NAMES_STD == "2"
replace NAMES_STD = "Angola" if NAMES_STD == "1"
replace NAMES_STD = "Antigua and Barbuda" if NAMES_STD == "5"
replace NAMES_STD = "Argentina" if NAMES_STD == "3"
replace NAMES_STD = "Armenia" if NAMES_STD == "4"
replace NAMES_STD = "Australia" if NAMES_STD == "6"
replace NAMES_STD = "Austria" if NAMES_STD == "7"
replace NAMES_STD = "Azerbaijan" if NAMES_STD == "8"
replace NAMES_STD = "Bahamas" if NAMES_STD == "16"
replace NAMES_STD = "Bahrain" if NAMES_STD == "15"
replace NAMES_STD = "Bangladesh" if NAMES_STD == "13"
replace NAMES_STD = "Barbados" if NAMES_STD == "22"
replace NAMES_STD = "Belarus" if NAMES_STD == "17"
replace NAMES_STD = "Belgium" if NAMES_STD == "10"
replace NAMES_STD = "Belize" if NAMES_STD == "18"
replace NAMES_STD = "Benin" if NAMES_STD == "11"
replace NAMES_STD = "Bermuda" if NAMES_STD == "19"
replace NAMES_STD = "Bhutan" if NAMES_STD == "23"
replace NAMES_STD = "Bolivia" if NAMES_STD == "20"
replace NAMES_STD = "Botswana" if NAMES_STD == "24"
replace NAMES_STD = "Brazil" if NAMES_STD == "21"
replace NAMES_STD = "Bulgaria" if NAMES_STD == "14"
replace NAMES_STD = "Burkina Faso" if NAMES_STD == "12"
replace NAMES_STD = "Burundi" if NAMES_STD == "9"
replace NAMES_STD = "Cambodia" if NAMES_STD == "85"
replace NAMES_STD = "Cameroon" if NAMES_STD == "31"
replace NAMES_STD = "Canada" if NAMES_STD == "26"
replace NAMES_STD = "Cape Verde" if NAMES_STD == "35"
replace NAMES_STD = "Central African Republic" if NAMES_STD == "25"
replace NAMES_STD = "Chad" if NAMES_STD == "146"
replace NAMES_STD = "Chile" if NAMES_STD == "28"
replace NAMES_STD = "China" if NAMES_STD == "29"
replace NAMES_STD = "Colombia" if NAMES_STD == "33"
replace NAMES_STD = "Comoros" if NAMES_STD == "34"
replace NAMES_STD = "Democratic Republic of Congo" if NAMES_STD == "166"
replace NAMES_STD = "Congo" if NAMES_STD == "32"
replace NAMES_STD = "Costa Rica" if NAMES_STD == "36"
replace NAMES_STD = "Croatia" if NAMES_STD == "69"
replace NAMES_STD = "Cuba" if NAMES_STD == "37"
replace NAMES_STD = "Cyprus" if NAMES_STD == "38"
replace NAMES_STD = "Czech Republic" if NAMES_STD == "39"
replace NAMES_STD = "Denmark" if NAMES_STD == "42"
replace NAMES_STD = "Djibouti" if NAMES_STD == "40"
replace NAMES_STD = "Dominica" if NAMES_STD == "41"
replace NAMES_STD = "Dominican Republic" if NAMES_STD == "43"
replace NAMES_STD = "Ecuador" if NAMES_STD == "45"
replace NAMES_STD = "Egypt" if NAMES_STD == "46"
replace NAMES_STD = "El Salvador" if NAMES_STD == "138"
replace NAMES_STD = "Equatorial Guinea" if NAMES_STD == "62"
replace NAMES_STD = "Eritrea" if NAMES_STD == "47"
replace NAMES_STD = "Estonia" if NAMES_STD == "49"
replace NAMES_STD = "Ethiopia" if NAMES_STD == "50"
replace NAMES_STD = "Fiji" if NAMES_STD == "52"
replace NAMES_STD = "Finland" if NAMES_STD == "51"
replace NAMES_STD = "France" if NAMES_STD == "53"
replace NAMES_STD = "Gabon" if NAMES_STD == "54"
replace NAMES_STD = "Gambia" if NAMES_STD == "60"
replace NAMES_STD = "Georgia" if NAMES_STD == "56"
replace NAMES_STD = "Germany" if NAMES_STD == "57"
replace NAMES_STD = "Ghana" if NAMES_STD == "58"
replace NAMES_STD = "Greece" if NAMES_STD == "63"
replace NAMES_STD = "Grenada" if NAMES_STD == "64"
replace NAMES_STD = "Guatemala" if NAMES_STD == "65"
replace NAMES_STD = "Guinea" if NAMES_STD == "59"
replace NAMES_STD = "Guinea-Bissau" if NAMES_STD == "61"
replace NAMES_STD = "Guyana" if NAMES_STD == "66"
replace NAMES_STD = "Haiti" if NAMES_STD == "70"
replace NAMES_STD = "Honduras" if NAMES_STD == "68"
replace NAMES_STD = "Hong Kong" if NAMES_STD == "67"
replace NAMES_STD = "Hungary" if NAMES_STD == "71"
replace NAMES_STD = "Iceland" if NAMES_STD == "76"
replace NAMES_STD = "India" if NAMES_STD == "73"
replace NAMES_STD = "Indonesia" if NAMES_STD == "72"
replace NAMES_STD = "Iran" if NAMES_STD == "75"
replace NAMES_STD = "Ireland" if NAMES_STD == "74"
replace NAMES_STD = "Israel" if NAMES_STD == "77"
replace NAMES_STD = "Italy" if NAMES_STD == "78"
replace NAMES_STD = "Cote d'Ivoire" if NAMES_STD == "30"
replace NAMES_STD = "Jamaica" if NAMES_STD == "79"
replace NAMES_STD = "Japan" if NAMES_STD == "81"
replace NAMES_STD = "Jordan" if NAMES_STD == "80"
replace NAMES_STD = "Kazakhstan" if NAMES_STD == "82"
replace NAMES_STD = "Kenya" if NAMES_STD == "83"
replace NAMES_STD = "South Korea" if NAMES_STD == "87"
replace NAMES_STD = "Kuwait" if NAMES_STD == "88"
replace NAMES_STD = "Kyrgyz Republic" if NAMES_STD == "84"
replace NAMES_STD = "Laos" if NAMES_STD == "89"
replace NAMES_STD = "Latvia" if NAMES_STD == "96"
replace NAMES_STD = "Lebanon" if NAMES_STD == "90"
replace NAMES_STD = "Lesotho" if NAMES_STD == "93"
replace NAMES_STD = "Lithuania" if NAMES_STD == "94"
replace NAMES_STD = "Luxembourg" if NAMES_STD == "95"
replace NAMES_STD = "Macao" if NAMES_STD == "97"
replace NAMES_STD = "Macedonia" if NAMES_STD == "102"
replace NAMES_STD = "Madagascar" if NAMES_STD == "100"
replace NAMES_STD = "Malawi" if NAMES_STD == "109"
replace NAMES_STD = "Malaysia" if NAMES_STD == "110"
replace NAMES_STD = "Mali" if NAMES_STD == "103"
replace NAMES_STD = "Malta" if NAMES_STD == "104"
replace NAMES_STD = "Mauritania" if NAMES_STD == "107"
replace NAMES_STD = "Mauritius" if NAMES_STD == "108"
replace NAMES_STD = "Mexico" if NAMES_STD == "101"
replace NAMES_STD = "Moldova" if NAMES_STD == "99"
replace NAMES_STD = "Mongolia" if NAMES_STD == "105"
replace NAMES_STD = "Morocco" if NAMES_STD == "98"
replace NAMES_STD = "Mozambique" if NAMES_STD == "106"
replace NAMES_STD = "Namibia" if NAMES_STD == "111"
replace NAMES_STD = "Nepal" if NAMES_STD == "117"
replace NAMES_STD = "Netherlands" if NAMES_STD == "115"
replace NAMES_STD = "New Zealand" if NAMES_STD == "118"
replace NAMES_STD = "Nicaragua" if NAMES_STD == "114"
replace NAMES_STD = "Niger" if NAMES_STD == "112"
replace NAMES_STD = "Nigeria" if NAMES_STD == "113"
replace NAMES_STD = "Norway" if NAMES_STD == "116"
replace NAMES_STD = "Oman" if NAMES_STD == "119"
replace NAMES_STD = "Pakistan" if NAMES_STD == "120"
replace NAMES_STD = "Panama" if NAMES_STD == "121"
replace NAMES_STD = "Papua New Guinea" if NAMES_STD == "124"
replace NAMES_STD = "Paraguay" if NAMES_STD == "128"
replace NAMES_STD = "Peru" if NAMES_STD == "122"
replace NAMES_STD = "Philippines" if NAMES_STD == "123"
replace NAMES_STD = "Poland" if NAMES_STD == "125"
replace NAMES_STD = "Portugal" if NAMES_STD == "127"
replace NAMES_STD = "Puerto Rico" if NAMES_STD == "126"
replace NAMES_STD = "Qatar" if NAMES_STD == "129"
replace NAMES_STD = "Romania" if NAMES_STD == "130"
replace NAMES_STD = "Russia" if NAMES_STD == "131"
replace NAMES_STD = "Rwanda" if NAMES_STD == "132"
replace NAMES_STD = "Saint Kitts and Nevis" if NAMES_STD == "86"
replace NAMES_STD = "Saint Lucia" if NAMES_STD == "91"
replace NAMES_STD = "Saint Vincent and the Grenadines" if NAMES_STD == "161"
replace NAMES_STD = "Sao Tome and Principe" if NAMES_STD == "139"
replace NAMES_STD = "Saudi Arabia" if NAMES_STD == "133"
replace NAMES_STD = "Senegal" if NAMES_STD == "135"
replace NAMES_STD = "Seychelles" if NAMES_STD == "144"
replace NAMES_STD = "Sierra Leone" if NAMES_STD == "137"
replace NAMES_STD = "Singapore" if NAMES_STD == "136"
replace NAMES_STD = "Slovak Republic" if NAMES_STD == "140"
replace NAMES_STD = "Slovenia" if NAMES_STD == "141"
replace NAMES_STD = "South Africa" if NAMES_STD == "165"
replace NAMES_STD = "Spain" if NAMES_STD == "48"
replace NAMES_STD = "Sri Lanka" if NAMES_STD == "92"
replace NAMES_STD = "Sudan" if NAMES_STD == "134"
replace NAMES_STD = "Swaziland" if NAMES_STD == "143"
replace NAMES_STD = "Sweden" if NAMES_STD == "142"
replace NAMES_STD = "Switzerland" if NAMES_STD == "27"
replace NAMES_STD = "Syria" if NAMES_STD == "145"
replace NAMES_STD = "Taiwan" if NAMES_STD == "154"
replace NAMES_STD = "Tajikistan" if NAMES_STD == "149"
replace NAMES_STD = "Tanzania" if NAMES_STD == "155"
replace NAMES_STD = "Thailand" if NAMES_STD == "148"
replace NAMES_STD = "Togo" if NAMES_STD == "147"
replace NAMES_STD = "Trinidad and Tobago" if NAMES_STD == "151"
replace NAMES_STD = "Tunisia" if NAMES_STD == "152"
replace NAMES_STD = "Turkey" if NAMES_STD == "153"
replace NAMES_STD = "Turkmenistan" if NAMES_STD == "150"
replace NAMES_STD = "Uganda" if NAMES_STD == "156"
replace NAMES_STD = "Ukraine" if NAMES_STD == "157"
replace NAMES_STD = "United Kingdom" if NAMES_STD == "55"
replace NAMES_STD = "United States" if NAMES_STD == "159"
replace NAMES_STD = "Uruguay" if NAMES_STD == "158"
replace NAMES_STD = "Uzbekistan" if NAMES_STD == "160"
replace NAMES_STD = "Venezuela" if NAMES_STD == "162"
replace NAMES_STD = "Yemen" if NAMES_STD == "164"
replace NAMES_STD = "Zambia" if NAMES_STD == "167"
replace NAMES_STD = "Zimbabwe" if NAMES_STD == "168"

end
exit
