{smcl}
{* version 1.0.0  05feb2025  Ben Jann}{...}
{hi:labels_isco88b()} {hline 2} Long ISCO-88 labels by Ganzeboom/Treiman

{title:Description}

{pstd}
    {helpb crosswalk} table providing labels for 4-digit ISCO-88 codes by
    Ganzeboom/Treiman (1996). The Ganzeboom/Treiman variant of ISCO-88 contains
    a few extra occupational codes compared to the official variant by the ILO.

{pstd}
    {cmd:labels_isco88b()} provides long labels; see
    {helpb _cwfcn_labels_isco88a:labels_isco88a()} for short labels.

{title:Source}

{pstd}
    File {bf:{browse "http://www.harryganzeboom.nl/ismf/scaleapp.htm":scaleapp.htm}}
    provided by Harry Ganzeboom at {browse "http://www.harryganzeboom.nl/isco88/"}.

{title:References}

{phang}
    Ganzeboom, H.B.G., D.J. Treiman. 1996. Internationally Comparable Measures
    of Occupational Status for the 1988 International Standard Classification
    of Occupations. Social Science Research 25: 201-239.
    {p_end}
{hline}
{asis}
1000 "LEGISLATORS, SENIOR OFFICIALS & MANAGERS"
1100 "LEGISLATORS & SENIOR OFFICIALS"
1110 "LEGISLATORS"
1120 "SENIOR [NATIONAL] GOVERNMENT OFFICIALS"
1130 "[SENIOR LOCAL GOVERNMENT OFFICIALS]"
1140 "SENIOR OFFICIALS SPECIAL-INTEREST ORGANISATIONS"
1141 "Senior officials political-party organisations"
1142 "Senior officials economic-interest organisations"
1143 "Senior officials special-interest organisations"
1200 "CORPORATE MANAGERS [LARGE ENTERPRISES]"
1210 "[LARGE ENTERPRISES] DIRECTORS & CHIEF EXECUTIVES"
1220 "[LARGE ENTERPRISE OPERATION] DEPARTMENT MANAGERS"
1221 "Production department managers agriculture & fishing"
1222 "Production department managers manufacturing"
1223 "Production department managers construction"
1224 "Production department managers wholesale & retail trade"
1225 "Production department managers restaurants & hotels"
1226 "Production department managers transp., storage & communic."
1227 "Production department managers business services"
1228 "Production department managers personal care, cleaning etc"
1229 "Production department managers nec"
1230 "[LARGE ENTERPRISES] OTHER DEPARTMENT MANAGERS"
1231 "Finance & administration department managers"
1232 "Personnel & industrial relations department managers"
1233 "Sales & marketing department managers"
1234 "Advertising & public relations department managers"
1235 "Supply & distribution department managers"
1236 "Computing services department managers"
1237 "Research & development department managers"
1239 "Other department managers nec"
1240 "OFFICE MANAGERS"
1250 "MILITARY OFFICERS"
1251 "Higher military officers"
1252 "Lower grade commissioned officers"
1300 "[SMALL ENTERPRISE] GENERAL MANAGERS"
1310 "[SMALL ENTERPRISE] GENERAL MANAGERS"
1311 "[Small enterprise] General managers agriculture, forestry & fishing"
1312 "[Small enterprise] General managers manufacturing"
1313 "[Small enterprise] General managers construction"
1314 "[Small enterprise] General managers wholesale & retail trade"
1315 "[Small enterprise] General managers restaurants & hotels"
1316 "[Small enterprise] General managers transp., storage & communications"
1317 "[Small enterprise] General managers business services"
1318 "[Small enterprise] General managers personal care, cleaning etc. services"
1319 "[Small enterprise] General managers nec"
2000 "PROFESSIONALS"
2100 "PHYSICAL, MATHEMATICAL & ENGINEERING SCIENCE PROFESSIONALS"
2110 "PHYSICISTS, CHEMISTS & RELATED PROFESSIONALS"
2111 "Physicists & astronomers"
2112 "Meteorologists"
2113 "Chemists"
2114 "Geologists & geophysicists"
2120 "MATHEMATICIANS, STATISTICIANS ETC PROFESSIONALS"
2121 "Mathematicians etc professionals"
2122 "Statisticians"
2130 "COMPUTING PROFESSIONALS"
2131 "Computer systems designers & analysts"
2132 "Computer programmers"
2139 "Computing professionals nec"
2140 "ARCHITECTS, ENGINEERS ETC PROFESSIONALS"
2141 "Architects town & traffic planners"
2142 "Civil engineers"
2143 "Electrical engineers"
2144 "Electronics & telecommunications engineers"
2145 "Mechanical engineers"
2146 "Chemical engineers"
2147 "Mining engineers, metallurgists etc professionals"
2148 "Cartographers & surveyors"
2149 "Architects engineers etc professionals nec"
2200 "LIFE SCIENCE & HEALTH PROFESSIONALS"
2210 "LIFE SCIENCE PROFESSIONALS"
2211 "Biologists, botanists zoologists etc professionals"
2212 "Pharmacologists, pathologists etc professlonals"
2213 "Agronomists etc professionals"
2220 "HEALTH PROFESSIONALS (EXCEPT NURSING)"
2221 "Medical doctors"
2222 "Dentists"
2223 "Veterinarians"
2224 "Pharmacists"
2229 "Health professionals except nursing nec"
2230 "NURSING & MIDWIFERY PROFESSIONALS"
2300 "TEACHING PROFESSIONALS"
2310 "HIGHER EDUCATION TEACHING PROFESSIONALS"
2320 "SECONDARY EDUCATION TEACHING PROFESSIONALS"
2321 "[Secondary teachers, academic track]"
2322 "[Secondary teachers, vocational track]"
2330 "PRIMARY & PRE-PRIMARY EDUCATION TEACHING PROFESSIONALS"
2331 "Primary education teaching professionals"
2332 "Pre-primary education teaching professionals"
2340 "SPECIAL EDUCATION TEACHING PROFESSIONALS"
2350 "OTHER TEACHING PROFESSIONALS"
2351 "Education methods specialists"
2352 "School inspectors"
2359 "Other teaching professionals nec"
2400 "OTHER PROFESSIONALS"
2410 "BUSINESS PROFESSIONALS"
2411 "Accountants"
2412 "Personnel & careers professionals"
2419 "Business professionals nec"
2420 "LEGAL PROFESSIONALS"
2421 "Lawyers"
2422 "Judges"
2429 "Legal professionals nec"
2430 "ARCHIVISTS, LIBRARIANS ETC INFORMATION PROFESSIONALS"
2431 "Archivists & curators"
2432 "Librarians etc information professionals"
2440 "SOCIAL SCIENCE ETC PROFESSIONALS"
2441 "Economists"
2442 "Sociologists, anthropologists etc professionals"
2443 "Philosophers, historians & political scientists"
2444 "Philologists, translators & interpreters"
2445 "Psychologists"
2446 "Social work professionals"
2450 "WRITERS & CREATIVE OR PERFORMING ARTISTS"
2451 "Authors journalists & other writers"
2452 "Sculptors, painters etc artists"
2453 "Composers, musicians & singers"
2454 "Choreographers & dancers"
2455 "Film, stage etc actors & directors"
2460 "RELIGIOUS PROFESSIONALS"
3000 "TECHNICIANS AND ASSOCIATE PROFESSIONALS"
3100 "PHYSICAL & ENGINEERING SCIENCE ASSOCIATE PROFESSIONALS"
3110 "PHYSICAL & ENGINEERING SCIENCE TECHNICIANS"
3111 "Chemical & physical science technicians"
3112 "Civil engineering technicians"
3113 "Electrical engineering technicians"
3114 "Electronics & telecommunications engineering technicians"
3115 "Mechanical engineering technicians"
3116 "Chemical engineering technicians"
3117 "Mining & metallurgical technicians"
3118 "Draughtspersons"
3119 "Physical & engineering science technicians nec"
3120 "COMPUTER ASSOCIATE PROFESSIONALS"
3121 "Computer assistants"
3122 "Computer equipment operators"
3123 "Industrial robot controllers"
3130 "OPTICAL & ELECTRONIC EQUIPMENT OPERATORS"
3131 "Photographers & electronic equipment operators"
3132 "Broadcasting & telecommunications equipment operators"
3133 "Medical equipment operators"
3139 "Optical & electronic equipment operators nec"
3140 "SHIP & AIRCRAFT CONTROLLERS & TECHNICIANS"
3141 "Ships engineers"
3142 "Ships deck officers & pilots"
3143 "Aircraft pilots etc associate professionals"
3144 "Air traffic controllers"
3145 "Air traffic safety technicians"
3150 "SAFETY & QUALITY INSPECTORS"
3151 "Building & fire inspectors"
3152 "Safety, health & quality inspectors"
3200 "LIFE SCIENCE & HEALTH ASSOCIATE PROFESSIONALS"
3210 "LIFE SCIENCE TECHNICIANS ETC ASSOCIATE PROFESSIONALS"
3211 "Life science technicians"
3212 "Agronomy & forestry technicians"
3213 "Farming & forestry advisers"
3220 "MODERN HEALTH ASSOCIATE PROFESSIONALS EXCEPT NURSING"
3221 "Medical assistants"
3222 "Sanitarians"
3223 "Dieticians & nutritionists"
3224 "Optometrists & opticians"
3225 "Dental assistants"
3226 "Physiotherapists etc associate professionals"
3227 "Veterinary assistants"
3228 "Pharmaceutical assistants"
3229 "Modern health associate professionals except nursing nec"
3230 "NURSING & MIDWIFERY ASSOCIATE PROFESSIONALS"
3231 "Nursing associate professionals"
3232 "Midwifery associate professionals"
3240 "TRADITIONAL MEDICINE PRACTITIONERS & FAITH HEALERS"
3241 "Traditional medicine practitioners"
3242 "Faith healers"
3300 "TEACHING ASSOCIATE PROFESSIONALS"
3310 "PRIMARY EDUCATION TEACHING ASSOCIATE PROFESSIONALS"
3320 "PRE-PRIMARY EDUCATION TEACHING ASSOCIATE PROFESSIONALS"
3330 "SPECIAL EDUCATION TEACHING ASSOCIATE PROFESSIONALS"
3340 "OTHER TEACHING ASSOCIATE PROFESSIONALS"
3400 "OTHER ASSOCIATE PROFESSIONALS"
3410 "FINANCE & SALES ASSOCIATE PROFESSIONALS"
3411 "Securities & finance dealers & brokers"
3412 "Insurance representatives"
3413 "[Real] estate agents"
3414 "Travel consultants & organisers"
3415 "Technical & commercial sales representatives"
3416 "Buyers"
3417 "Appraisers, valuers & auctioneers"
3419 "Finance & sales associate professionals nec"
3420 "BUSINESS SERVICES AGENTS AND TRADE BROKERS"
3421 "Trade brokers"
3422 "Clearing & forwarding agents"
3423 "Employment agents & labour contractors"
3429 "Business services agents & trade brokers nec"
3430 "ADMINISTRATIVE ASSOCIATE PROFESSIONALS"
3431 "Administrative secretaries etc associate professionals"
3432 "Legal etc business associate professlonals"
3433 "Bookkeepers"
3434 "Statistical, mathematical etc associate professionals"
3439 "Administrative associate professionals nec"
3440 "CUSTOMS, TAX ETC GOVERNMENT ASSOCIATE PROFESSIONALS"
3441 "Customs & border inspectors"
3442 "Government tax & excise officials"
3443 "Government social benefits officials"
3444 "Government licensing officials"
3449 "Customs tax etc government associate professionals nec"
3450 "POLICE INSPECTORS & DETECTIVES / [ARMY]"
3451 "Police inspectors & detectives"
3452 "[Armed forces non-commissioned officers]"
3460 "SOCIAL WORK ASSOCIATE PROFESSIONALS"
3470 "ARTISTIC, ENTERTAINMENT & SPORTS ASSOCIATE PROFESSIONALS"
3471 "Decorators & commercial designers"
3472 "Radio, television & other announcers"
3473 "Street night-club etc musicians, singers & dancers"
3474 "Clowns, magicians, acrobats etc associate professionals"
3475 "Athletes, sportspersons etc associate professionals"
3480 "RELIGIOUS ASSOCIATE PROFESSIONALS"
4000 "CLERKS"
4100 "OFFICE CLERKS"
4110 "SECRETARIES & KEYBOARD-OPERATING CLERKS"
4111 "Stenographers & typists"
4112 "Word-processor etc operators"
4113 "Data entry operators"
4114 "Calculating-machine operators"
4115 "Secretaries"
4120 "NUMERICAL CLERKS"
4121 "Accounting & bookkeeping clerks"
4122 "Statistical & finance clerks"
4130 "MATERIAL-RECORDING & TRANSPORT CLERKS"
4131 "Stock clerks"
4132 "Production clerks"
4133 "Transport clerks"
4140 "LIBRARY, MAIL ETC CLERKS"
4141 "Library & filing clerks"
4142 "Mail carriers & sorting clerks"
4143 "Coding proof-reading etc clerks"
4144 "Scribes etc workers"
4190 "OTHER OFFICE CLERKS"
4200 "CUSTOMER SERVICES CLERKS"
4210 "CASHIERS, TELLERS ETC CLERKS"
4211 "Cashiers & ticket clerks"
4212 "Tellers & other counter clerks"
4213 "Bookmakers & croupiers"
4214 "Pawnbrokers & money-lenders"
4215 "Debt-collectors etc workers"
4220 "CLIENT INFORMATION CLERKS"
4221 "Travel agency etc clerks"
4222 "Receptionists & information clerks"
4223 "Telephone switchboard operators"
5000 "SERVICE WORKERS & SHOP & MARKET SALES WORKERS"
5100 "PERSONAL & PROTECTIVE SERVICES WORKERS"
5110 "TRAVEL ATTENDANTS ETC"
5111 "Travel attendants & travel stewards"
5112 "Transport conductors"
5113 "Travel, museum guides"
5120 "HOUSEKEEPING & RESTAURANT SERVICES WORKERS"
5121 "Housekeepers etc workers"
5122 "Cooks"
5123 "Waiters, waitresses & bartenders"
5130 "PERSONAL CARE ETC WORK"
5131 "Child-care workers"
5132 "Institution-based personal care workers"
5133 "Home based personal care workers"
5139 "[Other] care etc workers nec"
5140 "OTHER PERSONAL SERVICES WORKERS"
5141 "Hairdressers, barbers, beauticians etc workers"
5142 "Companions & valets"
5143 "Undertakers & embalmers"
5149 "Other personal services workers nec"
5150 "ASTROLOGERS, FORTUNE-TELLERS ETC WORKERS"
5151 "Astrologers etc workers"
5152 "Fortune-tellers, palmists etc workers"
5160 "PROTECTIVE SERVICES WORKERS"
5161 "Fire-fighters"
5162 "Police officers"
5163 "Prison guards"
5164 "[Armed forces, soldiers]"
5169 "Protective services workers nec"
5200 "[SALESPERSONS, MODELS & DEMONSTRATORS]"
5210 "FASHION & OTHER MODELS"
5220 "SHOP SALESPERSONS & DEMONSTRATORS"
5230 "STALL & MARKET SALESPERSONS"
6000 "SKILLED AGRICULTURAL & FISHERY WORKERS"
6100 "MARKET-ORIENTED SKILLED AGRICULTURAL & FISHERY WORKERS"
6110 "MARKET GARDENERS & CROPGROWERS"
6111 "Field crop & vegetable growers"
6112 "Tree & shrub crop growers"
6113 "Gardeners, horticultural & nursery growers"
6114 "Mixed-crop growers"
6120 "MARKET-ORIENTED ANIMAL PRODUCERS ETC WORKERS"
6121 "Dairy & livestock producers"
6122 "Poultry producers"
6123 "Apiarists & sericulturists"
6124 "Mixed-animal producers"
6129 "Market-oriented animal producers etc workers nec"
6130 "MARKET-ORIENTED CROP & ANIMAL PRODUCERS"
6131 "[Mixed farmers]"
6132 "[Farm foremen/supervisor]"
6133 "[Farmers nfs]"
6134 "[Skilled farm workers nfs]"
6140 "FORESTRY ETC WORKERS"
6141 "Forestry workers & loggers"
6142 "Charcoal burners etc workers"
6150 "FISHERY WORKERS, HUNTERS & TRAPPERS"
6151 "Aquatic-life cultivation workers"
6152 "Inland & coastal waters fishery workers"
6153 "Deep-sea fishery workers"
6154 "Hunters & trappers"
6200 "SUBSISTENCE AGRICULTURAL & FISHERY WORKERS"
6210 "SUBSISTENCE AGRICULTURAL & FISHERY WORKERS"
7000 "CRAFT ETC TRADES WORKERS"
7100 "EXTRACTION & BUILDING TRADES WORKERS"
7110 "MINERS, SHOTFIRERS, STONE CUTTERS & CARVERS"
7111 "Miners & quarry workers"
7112 "Shotfirers & blasters"
7113 "Stone splitters, cutters & carvers"
7120 "BUILDING FRAME ETC TRADES WORKERS"
7121 "Builders traditional materials"
7122 "Bricklayers & stonemasons"
7123 "Concrete placers, concrete finishers etc workers"
7124 "Carpenters & joiners"
7129 "Building frame etc trades workers nec"
7130 "BUILDING FINISHERS ETC TRADES WORKERS"
7131 "Roofers"
7132 "Floor layers & tile setters"
7133 "Plasterers"
7134 "Insulation workers"
7135 "Glaziers"
7136 "Plumbers & pipe fitters"
7137 "Building etc electricians"
7140 "PAINTERS, BUILDING STRUCTURE CLEANERS ETC TRADES WORKERS"
7141 "Painters etc workers"
7142 "Varnishers etc painters"
7143 "Building structure cleaners"
7200 "METAL, MACHINERY ETC TRADES WORKERS"
7210 "METAL MOULDERS, WELDERS, SHEETMETAL WORKERS STRUCTURAL METAL"
7211 "Metal moulders & coremakers"
7212 "Welders & flamecutters"
7213 "Sheet-metal workers"
7214 "Structural-metal preparers & erectors"
7215 "Riggers & cable splicers"
7216 "Underwater workers"
7220 "BLACKSMITHS, TOOL-MAKERS ETC TRADES WORKERS"
7221 "Blacksmiths, hammer-smiths & forging press workers"
7222 "Tool-makers etc workers"
7223 "Machine-tool setters & setter-operators"
7224 "Metal wheel-grinders, polishers & tool sharpeners"
7230 "MACHINERY MECHANICS & FITTERS"
7231 "Motor vehicle mechanics & fitters"
7232 "Aircraft engine mechanics & fitters"
7233 "[Industrial & agricultural] machinery mechanics & fitters"
7234 "[Unskilled garage worker]"
7240 "ELECTRICAL & ELECTRONIC EQUIPMENT MECHANICS & FITTERS"
7241 "Electrical mechanics & fitters"
7242 "Electronics fitters"
7243 "Electronics mechanics & servicers"
7244 "Telegraph & telephone installers & servicers"
7245 "Electrical line installers, repairers & cable jointers"
7300 "PRECISION, HANDICRAFT, PRINTING ETC TRADES WORKERS"
7310 "PRECISION WORKERS IN METAL ETC MATERIALS"
7311 "Precision-instrument makers & repairers"
7312 "Musical-instrument makers & tuners"
7313 "Jewellery & precious-metal workers"
7320 "POTTERS, GLASS-MAKERS ETC TRADES WORKERS"
7321 "Abrasive wheel formers, potters etc workers"
7322 "Glass-makers, cutters, grinders & finishers"
7323 "Glass engravers & etchers"
7324 "Glass ceramics etc decorative painters"
7330 "HANDICRAFT WORKERS IN WOOD,TEXTILE, LEATHER ETC"
7331 "Handicraft workers in wood etc materials"
7332 "Handicraft workers in textile leather etc materials"
7340 "PRINTING ETC TRADES WORKERS"
7341 "Compositors typesetters etc workers"
7342 "Stereotypers & electrotypers"
7343 "Printing engravers & etchers"
7344 "Photographic etc workers"
7345 "Bookbinders etc workers"
7346 "Silk-screen, block & textile printers"
7400 "OTHER CRAFT ETC TRADES WORKERS"
7410 "FOOD PROCESSING ETC TRADES WORKERS"
7411 "Butchers, fishmongers etc food preparers"
7412 "Bakers, pastry-cooks & confectionery makers"
7413 "Dairy-products makers"
7414 "Fruit, vegetable etc preservers"
7415 "Food & beverage tasters & graders"
7416 "Tobacco preparers & tobacco products makers"
7420 "WOOD TREATERS, CABINET-MAKERS ETC TRADES WORKERS"
7421 "Wood treaters"
7422 "Cabinet-makers etc workers"
7423 "Woodworking-machine setters & setter-operators"
7424 "Basketry weavers, brush makers etc workers"
7430 "TEXTILE, GARMENT ETC TRADES WORKERS"
7431 "Fibre preparers"
7432 "Weavers, knitters etc workers"
7433 "Tailors, dressmakers & hatters"
7434 "Furriers etc workers"
7435 "Textile, leather etc pattern-makers & cutters"
7436 "Sewers, embroiderers etc workers"
7437 "Upholsterers etc workers"
7440 "PELT, LEATHER & SHOEMAKING TRADES WORKERS"
7441 "Pelt dressers, tanners & fellmongers"
7442 "Shoe-makers etc workers"
7500 "[SKILLED WORKERS NFS]"
7510 "[MANUAL FOREMEN NFS --NON-FARM--]"
7520 "[SKILLED WORKERS NFS]"
7530 "[APPRENTICE SKILLED WORK NFS]"
8000 "PLANT & MACHINE OPERATORS & ASSEMBLERS"
8100 "STATIONARY-PLANT ETC OPERATORS"
8110 "MINING- & MINERAL-PROCESSING PLANT OPERATORS"
8111 "Mining-plant operators"
8112 "Mineral-ore- & stone-processing-plant operators"
8113 "Well drillers & borers etc workers"
8120 "METAL-PROCESSING-PLANT OPERATORS"
8121 "Ore & metal furnace operators"
8122 "Metal melters, casters & rolling-mill operators"
8123 "Metal-heat-treating-plant operators"
8124 "Metal drawers & extruders"
8130 "GLASS, CERAMICS ETC PLANT OPERATORS"
8131 "Glass & ceramics kiln etc machine operators"
8139 "Glass, ceramics etc plant operators nec"
8140 "WOOD-PROCESSING- & PAPERMAKING-PLANT OPERATORS"
8141 "Wood-processing-plant operators"
8142 "Paper-pulp plant operators"
8143 "Papermaking-plant operators"
8150 "CHEMICAL-PROCESSING-PLANT OPERATORS"
8151 "Crushing- grinding- & chemical-mixing machinery operators"
8152 "Chemical-heat-treating-plant operators"
8153 "Chemical-filtering- & separating-equipment operators"
8154 "Chemical-still & reactor operators"
8155 "Petroleum- & natural-gas-refining-plant operators"
8159 "Chemical-processing-plant operators nec"
8160 "POWER-PRODUCTION ETC PLANT OPERATORS"
8161 "Power-production plant operators"
8162 "Steam-engine & boiler operators"
8163 "Incinerator water-treatment etc plant operators"
8170 "AUTOMATED-ASSEMBLY-LINE & INDUSTRIAL-ROBOT OPERATORS"
8171 "Automated-assembly-line operators"
8172 "Industrial-robot operators"
8200 "MACHINE OPERATORS & ASSEMBLERS"
8210 "METAL- & MINERAL-PRODUCTS MACHINE OPERATORS"
8211 "Machine-tool operators"
8212 "Cement & other mineral products machine operators"
8220 "CHEMICAL-PRODUCTS MACHINE OPERATORS"
8221 "Pharmaceutical- & toiletry-products machine operators"
8222 "Ammunition- & explosive-products machine operators"
8223 "Metal finishing- plating- & coating-machine operators"
8224 "Photographic-products machine operators"
8229 "Chemical-products machine operators nec"
8230 "RUBBER- & PLASTIC-PRODUCTS MACHINE OPERATORS"
8231 "Rubber-products machine operators"
8232 "Plastic-products machine operators"
8240 "WOOD-PRODUCTS MACHINE OPERATORS"
8250 "PRINTING-, BINDING- & PAPER-PRODUCTS MACHINE OPERATORS"
8251 "Printing-machine operators"
8252 "Bookbinding-machine operators"
8253 "Paper-products machine operators"
8260 "TEXTILE-, FUR- & LEATHER-PRODUCTS MACHINE OPERATORS"
8261 "Fibre-preparing-, spinning- & winding machine operators"
8262 "Weaving- & knitting-machine operators"
8263 "Sewing-machine operators"
8264 "Bleaching-, dyeing- & cleaning-machine operators"
8265 "Fur- & leather-preparing-machine operators"
8266 "Shoemaking- etc machine operators"
8269 "Textile-, fur- & leather-products machine operators nec"
8270 "FOOD ETC PRODUCTS MACHINE OPERATORS"
8271 "Meat- & fish-processing-machine operators"
8272 "Dairy-products machine operators"
8273 "Grain- & spice-milling-machine operators"
8274 "Baked-goods cereal & chocolate-products machine operators"
8275 "Fruit-, vegetable- & nut-processing-machine operators"
8276 "Sugar production machine operators"
8277 "Tea-, coffee- & cocoa-processing-machine operators"
8278 "Brewers- wine & other beverage machine operators"
8279 "Tobacco production machine operators"
8280 "ASSEMBLERS"
8281 "Mechanical-machinery assemblers"
8282 "Electrical-equipment assemblers"
8283 "Electronic-equipment assemblers"
8284 "Metal-, rubber- & plastic-products assemblers"
8285 "Wood etc products assemblers"
8286 "Paperboard, textile etc products assemblers"
8290 "OTHER MACHINE OPERATORS & ASSEMBLERS"
8300 "DRIVERS & MOBILE-PLANT OPERATORS"
8310 "LOCOMOTIVE-ENGINE DRIVERS ETC WORKERS"
8311 "Locomotive-engine drivers"
8312 "Railway brakers signallers & shunters"
8320 "MOTOR-VEHICLE DRIVERS"
8321 "Motor-cycle drivers"
8322 "Car, taxi & van drivers"
8323 "Bus & tram drivers"
8324 "Heavy truck & lorry drivers"
8330 "AGRICULTURAL & OTHER MOBILE PLANT OPERATORS"
8331 "Motorised farm & forestry plant operators"
8332 "Earth-moving- etc plant operators"
8333 "Crane, hoist etc plant operators"
8334 "Lifting-truck operators"
8340 "SHIPS DECK CREWS ETC WORKERS"
8400 "SEMI-SKILLED WORKERS NFS"
9000 "ELEMENTARY OCCUPATIONS"
9100 "SALES & SERVICES ELEMENTARY OCCUPATIONS"
9110 "STREET VENDORS ETC WORKERS"
9111 "Street food vendors"
9112 "Street vendors non-food products"
9113 "Door-to-door & telephone salespersons"
9120 "STREET SERVICES ELEMENTARY OCCUPATIONS"
9130 "DOMESTIC ETC HELPERS CLEANERS & LAUNDERERS"
9131 "Domestic helpers & cleaners"
9132 "Helpers & cleaners in establishments"
9133 "Hand-launderers & pressers"
9140 "BUILDING CARETAKERS, WINDOW ETC CLEANERS"
9141 "Building caretakers"
9142 "Vehicle, window etc cleaners"
9150 "MESSENGERS, PORTERS, DOORKEEPERS ETC WORKERS"
9151 "Messengers, package & luggage porters & deliverers"
9152 "Doorkeepers, watchpersons etc workers"
9153 "Vending-machine money collectors, meter readers etc workers"
9160 "GARBAGE COLLECTORS ETC LABOURERS"
9161 "Garbage collectors"
9162 "Sweepers etc labourers"
9200 "AGRICULTURAL, FISHERY ETC LABOURERS"
9210 "AGRICULTURAL, FISHERY ETC LABOURERS"
9211 "Farm-hands & labourers"
9212 "Forestry labourers"
9213 "Fishery, hunting & trapping labourers"
9300 "LABOURERS IN MINING, CONSTRUCTION, MANUFACTURING & TRANSPORT"
9310 "MINING & CONSTRUCTION LABOURERS"
9311 "Mining & quarrying labourers"
9312 "Construction & maintenance labourers: roads dams etc"
9313 "Building construction labourers"
9320 "MANUFACTURING LABOURERS"
9321 "Assembling labourers"
9322 "Handpackers & other manufacturing labourers"
9330 "TRANSPORT LABOURERS & FREIGHT HANDLERS"
9331 "Hand or pedal vehicle drivers"
9332 "Drivers of animal-drawn vehicles & machinery"
9333 "Freight handlers"
