{smcl}
{* version 01.0.0 10apr2025 Hans Gerhardt and Anneke Kappes}{...}
{hi:labels_kldb88_3d()} {hline 2} KldB-1988 labels (3 digits)

{title:Description}

{pstd}
    {helpb kldbrecode} table providing labels for 3-digit KldB-1988 codes.

{title:Source}

{pstd}
    File {bf:{browse "https://metadaten.bibb.de/download/txt/604_20160413_1460534478/label_KldB88_eng_stata":label_KldB88_eng_stata.txt}}
    provided by the Federal Institute for Vocational Education and Training (BIBB) at {browse "https://metadaten.bibb.de/en/classification/detail/5"}.
    {p_end}

{hline}
{asis}
011 "Farmers"
012 "Winegrowers"
021 "Animal breeders"
022 "Fishermen"
031 "Managers in agriculture and animal breeding"
032 "Agricultural engineers, agriculture advisors"
041 "Land workers"
042 "Milkers"
043 "Family-member land workers, n.e.c."
044 "Animal keepers and related occupations"
051 "Gardeners, garden workers"
052 "Garden architects, garden managers"
053 "Florists"
061 "Forestry managers, foresters, hunters"
062 "Forest workers, forest cultivators"
071 "Miners"
072 "Mechanical, electrical, face workers, shot firers"
081 "Stone crushers"
082 "Earth, gravel, sand quarriers"
083 "Oil, natural gas quarriers"
091 "Mineral preparers, mineral burners"
101 "Stone preparers"
102 "Jewel preparers"
111 "Stoneware, earthenware makers"
112 "Shaped brick, concrete block makers"
121 "Ceramics workers"
131 "Frit makers"
132 "Hollow glassware makers"
133 "Flat glass makers"
134 "Glass blowers (lamps)"
135 "Glass processors, glass finishers"
141 "Chemical plant operatives"
142 "Chemical laboratory workers"
143 "Rubber makers, processors"
144 "Vulcanisers"
151 "Plastics processors"
161 "Paper, cellulose makers"
162 "Packaging makers"
163 "Book binding occupations"
164 "Other paper products makers"
171 "Type setters, compositors"
172 "Printed goods makers"
173 "Printers (letterpress)"
174 "Printers (flat, gravure)"
175 "Special printers, screeners"
176 "Copiers"
177 "Printer's assistants"
181 "Wood preparers"
182 "Wood moulders and related occupations"
183 "Wood products makers"
184 "Basket and wicker products makers"
191 "Iron, metal producers, melters"
192 "Rollers"
193 "Metal drawers"
201 "Moulders, coremakers"
202 "Mould casters"
203 "Semi-finished product fettlers and other mould casting occupations"
211 "Sheet metal pressers, drawers, stampers"
212 "Wire moulders, processors"
213 "Other metal moulders (non-cutting deformation)"
221 "Turners"
222 "Drillers"
223 "Planers"
224 "Borers"
225 "Metal grinders"
226 "Other metal-cutting occupations"
231 "Metal polishers"
232 "Engravers, chasers"
233 "Metal finishers"
234 "Galvanisers, metal colourers"
235 "Enamellers, zinc platers and other metal surface finishers"
241 "Welders, oxy-acetylene cutters"
242 "Solderers"
243 "Riveters"
244 "Metal bonders and other metal connectors"
251 "Steel smiths"
252 "Container builders, coppersmiths and related occupations"
261 "Sheet metal workers"
262 "Plumbers"
263 "Pipe, tubing fitters"
270 "Locksmiths, not specified"
271 "Building fitters"
272 "Sheet metal, plastics fitters"
273 "Engine fitters"
274 "Plant fitters, maintenance fitters"
275 "Steel structure fitters, metal shipbuilders"
281 "Motor vehicle repairers"
282 "Agricultural machinery repairers"
283 "Aircraft mechanics"
284 "Precision mechanics"
285 "Other mechanics"
286 "Watch-, clockmakers"
291 "Toolmakers"
301 "Precision fitters n.e.c."
302 "Precious metal smiths"
303 "Dental technicians"
304 "Opthalmic opticians"
305 "Musical instrument makers"
306 "Doll makers, model makers, taxidermists"
311 "Electrical fitters, mechanics"
312 "Telecommunications mechanics, craftsmen"
313 "Electric motor, transformer fitters"
314 "Electrical appliance fitters"
315 "Radio, sound equipment mechanics"
321 "Electrical appliance, electrical parts assemblers"
322 "Other assemblers"
323 "Metal workers (no further specification)"
331 "Spinners, fibre preparers"
332 "Spoolers, twisters, ropemakers"
341 "Weaving preparers"
342 "Weavers"
343 "Tufted goods makers"
344 "Machined goods makers"
345 "Felt makers, hat body makers"
346 "Textile processing operatives (braiders)"
351 "Cutters"
352 "Clothing sewers"
353 "Laundry cutters, sewers"
354 "Embroiderers"
355 "Hat, cap makers"
356 "Sewers, n.e.c."
357 "Other textile processing operatives"
361 "Textile dyers"
362 "Textile finishers"
371 "Leather makers, catgut string makers"
372 "Shoemakers"
373 "Footwear makers"
374 "Coarse leather goods finishers, truss makers"
375 "Fine leather goods makers"
376 "Leather clothing makers and other leather processing operatives"
377 "Hand shoemakers"
378 "Skin processing operatives"
391 "Bakery goods makers"
392 "Confectioners (pastry)"
401 "Butchers"
402 "Meat, sausage goods makers"
403 "Fish processing operatives"
411 "Cooks"
412 "Ready-to-serve meals, fruit, vegetable preservers, preparers"
421 "Wine coopers"
422 "Brewers, maltsters"
423 "Other beverage makers, tasters"
424 "Tobacco goods makers"
431 "Milk, fat processing operatives"
432 "Flour, food processors"
433 "Sugar, sweets, ice-cream makers"
441 "Bricklayers"
442 "Concrete workers"
451 "Carpenters"
452 "Roofers"
453 "Scaffolders"
461 "Paviors"
462 "Road makers"
463 "Tracklayers"
464 "Explosives men (except shotfirers)"
465 "Land improvement, hydraulic engineering workers"
466 "Other civil engineering workers"
470 "Building labourer, general"
471 "Earth movers"
472 "Other building labourers, building assistants, n.e.c."
481 "Stucco workers, plasterers, rough casters"
482 "Insulators, proofers"
483 "Tile setters"
484 "Furnace setter, air heating installers"
485 "Glaziers"
486 "Screed, terrazzo layers"
491 "Room equippers"
492 "Upholsterers, mattress makers"
501 "Carpenters"
502 "Model, form carpenters"
503 "Cartwrights, wheelwrights, coopers"
504 "Other wood and sports equipment makers"
511 "Painters, lacquerers (construction)"
512 "Goods painters, lacquerers"
513 "Wood surface finishers, veneerers"
514 "Ceramics, glass painters"
521 "Goods examiners, sorters, n.e.c."
522 "Packagers, goods receivers, despatchers"
531 "Assistants (no further specification)"
541 "Generator machinists"
542 "Winding engine drivers, aerial ropeway machinists"
543 "Other machinists"
544 "Crane drivers"
545 "Earthmoving plant drivers"
546 "Construction machine attendants"
547 "Machine attendants, machinists' helpers"
548 "Stokers"
549 "Machine setters (no further specification)"
555 "Disabled"
601 "Mechanical, motor engineers"
602 "Electrical engineers"
603 "Architects, civil engineers"
604 "Survey engineers"
605 "Mining, metallurgy, foundry engineers"
606 "Other manufacturing engineers"
607 "Other engineers"
611 "Chemists, chemical engineers"
612 "Physicists, physics engineers, mathematicians"
621 "Mechanical engineering technicians"
622 "Electrical engineering technicians"
623 "Building technicians"
624 "Measurement technicians"
625 "Mining, metallurgy, foundry technicians"
626 "Chemistry, physics technicians"
627 "Remaining manufacturing technicians"
628 "Other technicians"
629 "Foremen, master mechanics"
631 "Biological specialists"
632 "Physical and mathematical specialists"
633 "Chemical laboratory assistants"
634 "Photo laboratory assistants"
635 "Technical draughtspersons"
666 "Rehabilitants"
681 "Wholesale and retail trade buyers, buyers"
682 "Salespersons"
683 "Publishing house dealers, booksellers"
684 "Druggists/chemists (pharmacy)"
685 "Pharmacy aids"
686 "Service-station attendants"
687 "Commercial agents, travellers"
688 "Mobile traders"
691 "Bank specialists"
692 "Building society specialists"
693 "Health insurance specialists (not social security)"
694 "Life, property insurance specialists"
701 "Forwarding business dealers"
702 "Tourism specialists"
703 "Publicity occupations"
704 "Brokers, property managers"
705 "Landlords, agents, auctioneers"
706 "Cash collectors, cashiers, ticket sellers, inspectors"
711 "Railway engine drivers"
712 "Railway controllers, conductors"
713 "Other traffic controllers, conductors"
714 "Motor vehicle drivers"
715 "Coachmen"
716 "Street attendants"
721 "Navigating ships officers"
722 "Technical ships officers, ships engineers"
723 "Deck seamen"
724 "Inland boatmen"
725 "Other water transport occupations"
726 "Air transport occupations"
731 "Post masters"
732 "Postal deliverers"
733 "Radio operators"
734 "Telephonists"
741 "Warehouse managers, warehousemen"
742 "Transportation equipment drivers"
743 "Stowers, furniture packers"
744 "Stores, transport workers"
751 "Entrepreneurs, managing directors, divisional managers"
752 "Management consultants, organisors"
753 "Chartered accountants, tax advisers"
761 "Members of Parliament, Ministers, elected officials"
762 "Senior government officials"
763 "Association leaders, officials"
771 "Cost accountants, valuers"
772 "Accountants"
773 "Cashiers"
774 "Data processing specialists"
781 "Office specialists"
782 "Stenographers, shorthand-typists, typists"
783 "Data typists"
784 "Office auxiliary workers"
791 "Factory guards, detectives"
792 "Watchmen, custodians"
793 "Doormen, caretakers"
794 "Domestic and non-domestic servants"
801 "Soldiers, border guards, police officers"
802 "Firefighters"
803 "Safety testers"
804 "Chimney sweeps"
805 "Health-protecting occupations"
811 "Arbitrators"
812 "Judicial administrators"
813 "Legal representatives, advisors"
814 "Judicial enforcers"
821 "Journalists"
822 "Interpreters, translators"
823 "Librarians, archivists, museum specialists"
831 "Musicians"
832 "Artists' agents"
833 "Visual, commercial artists"
834 "Scenery, sign painters"
835 "Artistic and assisting occupations (stage, video and audio)"
836 "Interior, exhibition designers, window dressers"
837 "Photographers"
838 "Performers, professional sportsmen, auxiliary artistic occupations"
841 "Physicians"
842 "Dentists"
843 "Veterinary surgeons"
844 "Pharmacists"
851 "Non-medical practitioners"
852 "Masseurs, physiotherapists and related occupations"
853 "Nurses, midwives"
854 "Nursing assistants"
855 "Dietary assistants, pharmaceutical assistants"
856 "Medical receptionists"
857 "Medical laboratory assistants"
861 "Social workers, care workers"
862 "Home wardens, social work teachers"
863 "Work, vocational advisers"
864 "Nursery teachers, child nurses"
871 "University teachers, lecturers at higher technical schools and academies"
872 "Gymnasium teachers"
873 "Primary, secondary (basic), special school teachers"
874 "Technical, vocational, factory instructors"
875 "Music teachers, n.e.c."
876 "Sports teachers"
877 "Other teachers"
881 "Economic and social scientists, statisticians"
882 "Humanities specialists, n.e.c."
883 "Scientists n.e.c."
888 "Nursing staff"
891 "Ministers of religion"
892 "Members of religious orders without specific occupation"
893 "Religious care helpers"
901 "Hairdressers"
902 "Other body care occupations"
911 "Restaurant, inn, bar keepers, hotel proprietors, catering trade dealers"
912 "Waiters, stewards"
913 "Others attending on guests"
921 "Housekeeping managers"
922 "Consumer advisors"
923 "Other housekeeping attendants"
924 "Employees by household cheque procedure"
931 "Laundry workers, pressers"
932 "Textile cleaners, dyers and dry cleaners"
933 "Household cleaners"
934 "Glass, buildings cleaners"
935 "Street cleaners, refuse disposers"
936 "Vehicle cleaners, servicers"
937 "Machinery, container cleaners and related occupations"
971 "Non-agricultural family assistants, n.e.c."
981 "Trainees with recognised training occupation still to be specified"
982 "Interns, unpaid trainees with recognised training occupation still to be specified"
983 "Workforce (job seekers) with occupation still to be specified"
991 "Workforce not further specified"
995 "Recipients of early retirement pension"
996 "Employees in partial retirement"
997 "Recipients of compensations allowance"
999 "No Information"
