{smcl}
{* *! version 1.0.0  25feb2026}{...}
{vieweralsosee "xtpqardl" "help xtpqardl"}{...}
{vieweralsosee "xtpmg" "help xtpmg"}{...}
{vieweralsosee "xtdcce2" "help xtdcce2"}{...}
{vieweralsosee "qreg" "help qreg"}{...}
{viewerjumpto "Syntax" "xtcspqardl##syntax"}{...}
{viewerjumpto "Description" "xtcspqardl##description"}{...}
{viewerjumpto "Estimators" "xtcspqardl##estimators"}{...}
{viewerjumpto "Options" "xtcspqardl##options"}{...}
{viewerjumpto "Examples" "xtcspqardl##examples"}{...}
{viewerjumpto "Stored results" "xtcspqardl##results"}{...}
{viewerjumpto "References" "xtcspqardl##references"}{...}
{viewerjumpto "Author" "xtcspqardl##author"}{...}

{title:Title}

{p2colset 5 24 26 2}{...}
{p2col:{bf:xtcspqardl} {hline 2}}Cross-Sectionally Augmented Panel Quantile ARDL, Quantile CCE Mean Group, and Quantile CCE Pooled Mean Group Estimation{p_end}
{p2colreset}{...}


{marker syntax}{...}
{title:Syntax}

{pstd}{bf:CS-PQARDL Estimator (default):}{p_end}

{p 8 17 2}
{cmd:xtcspqardl}
{depvar} {indepvars}
{ifin}
{cmd:,} {opt tau(numlist)} {opt lr(varlist)}
[{it:cs-pqardl_options}]

{pstd}{bf:QCCEMG Estimator:}{p_end}

{p 8 17 2}
{cmd:xtcspqardl}
{depvar} {indepvars}
{ifin}
{cmd:,} {opt tau(numlist)} {opt qccemg}
[{it:qccemg_options}]

{pstd}{bf:QCCEPMG Estimator:}{p_end}

{p 8 17 2}
{cmd:xtcspqardl}
{depvar} {indepvars}
{ifin}
{cmd:,} {opt tau(numlist)} {opt qccepmg}
[{it:qccepmg_options}]

{synoptset 28 tabbed}{...}
{synopthdr}
{synoptline}
{syntab:Required}
{synopt:{opt tau(numlist)}}quantiles for estimation, e.g., {cmd:tau(0.25 0.5 0.75)}{p_end}

{syntab:Estimator Selection}
{synopt:{opt qccemg}}use Quantile CCE Mean Group estimator (Harding, Lamarche & Pesaran 2018){p_end}
{synopt:{opt qccepmg}}use Quantile CCE Pooled Mean Group estimator (Pesaran 2006; HLP 2018){p_end}
{synopt:{opt lr(varlist)}}long-run level variables for CS-PQARDL;
   first variable is the lagged dependent (ECT), remaining are long-run regressors{p_end}

{syntab:CS-PQARDL Options}
{synopt:{opt pmg}}Pooled Mean Group estimator (default){p_end}
{synopt:{opt mg}}Mean Group estimator{p_end}
{synopt:{opt dfe}}Dynamic Fixed Effects estimator{p_end}
{synopt:{opt p(#)}}autoregressive lag order; default is {cmd:p(1)}{p_end}
{synopt:{opt q(numlist)}}distributed lag orders; single number or per-variable{p_end}
{synopt:{opt ecm}}use ECM reparameterization; CSA in ECT only{p_end}
{synopt:{opt lagsel(string)}}automatic lag selection: {cmd:aic}, {cmd:bic}, or {cmd:both}{p_end}
{synopt:{opt pmax(#)}}maximum AR lag for lag selection; default is {cmd:pmax(4)}{p_end}
{synopt:{opt qmax(#)}}maximum DL lag for lag selection; default is {cmd:qmax(4)}{p_end}

{syntab:Cross-Sectional Dependence}
{synopt:{opt cr_lags(#)}}number of CSA lags (pT); default is floor(T^{1/3}){p_end}

{syntab:Advanced Analysis}
{synopt:{opt full}}perform advanced analysis, including quantile homogeneity test{p_end}
{synopt:{opt graph}}generate graphs: quantile process, ECT heatmap, half-life{p_end}

{syntab:Display}
{synopt:{opt show:individual}}display per-panel estimates{p_end}
{synopt:{opt showcsa}}display Cross-Sectional Average (CSA) nuisance coefficients{p_end}
{synopt:{opt notable}}suppress coefficient tables{p_end}
{synopt:{opt nocons:tant}}suppress constant term{p_end}
{synopt:{opt level(#)}}confidence level; default is {cmd:level(95)}{p_end}
{synoptline}
{p2colreset}{...}

{p 4 6 2}
Data must be declared as panel data using {cmd:xtset} {it:panelvar} {it:timevar}
before calling {cmd:xtcspqardl}.{p_end}


{marker description}{...}
{title:Description}

{pstd}
{cmd:xtcspqardl} implements two estimators for dynamic heterogeneous panel data
models with cross-sectional dependence at the quantile level:

{phang}
{bf:1. CS-PQARDL} (Cross-Sectionally Augmented Panel Quantile ARDL):
Extends the panel quantile ARDL framework by augmenting unit-specific
regressions with cross-sectional averages (CSA) of the dependent and independent
variables, following Pesaran (2006) and Chudik and Pesaran (2015). This absorbs
unobserved common factors that induce cross-sectional dependence, producing
consistent estimates under factor structures. CSA enter the long-run equation
(or ECT in ECM form), but are excluded from short-run dynamics.

{phang}
{bf:2. QCCEMG} (Quantile CCE Mean Group):
Implements the Quantile Common Correlated Effects Mean Group estimator of
Harding, Lamarche, and Pesaran (2018). This is a dynamic panel quantile
regression model where unobserved common factors are proxied by CSA and their
lags. Unit-specific quantile regressions are averaged using the Mean Group
approach, with inference based on the nonparametric between-group variance
(Theorem 4 of HLP 2018).

{pstd}
Both estimators handle heterogeneous slope coefficients across panels,
permit quantile-varying parameters, and are robust to cross-sectional
dependence generated by unobserved common factors.

{phang}
{bf:3. QCCEPMG} (Quantile CCE Pooled Mean Group):
Implements the pooled version of the QCCEMG estimator, following Pesaran (2006)
CCEP methodology adapted to the quantile setting. Individual quantile regressions
are estimated identically to QCCEMG, but the Mean Group averaging and inference
follow the Pooled Mean Group approach. Under slope homogeneity, the QCCEPMG
estimator achieves √(NT) convergence compared to √N for QCCEMG.

{pstd}
All three estimators handle heterogeneous slope coefficients across panels,
permit quantile-varying parameters, and are robust to cross-sectional
dependence generated by unobserved common factors.
{title:Estimators}

{pstd}
{bf:CS-PQARDL Model:}

{p 8 8 2}
Q_tau(y_it | X_it, z_bar_t) = rho_i(tau) * LR_vars + phi_i(tau) * AR_lags
+ gamma_i(tau) * SR_lags + delta_i(tau) * CSA + alpha_i(tau)

{pstd}
where CSA = (y_bar_t, x1_bar_t, ..., xk_bar_t, L.y_bar_t, ..., L_pT.y_bar_t, ...)
are cross-sectional averages and their lags. Long-run coefficients
beta_j(tau) = -coef(x_j)/rho(tau) are computed from the ARDL representation.

{pstd}
{bf:ECM reparameterization} ({cmd:ecm} option):

{p 8 8 2}
Delta y_it = phi_i(tau) * [y_{i,t-1} - theta'_i(tau) * x_{i,t-1}
- delta'_i(tau) * z_bar_{t-1}] + c_ij(tau) * Delta y_{i,t-j}
+ d_im(tau) * Delta x_{k,i,t-m} + e_it(tau)

{pstd}
CSA enter the error correction term only; short-run CSA differences are dropped.

{pstd}
{bf:QCCEMG Model} (Harding, Lamarche & Pesaran 2018, eq. 2.17):

{p 8 8 2}
y_it = alpha_i(tau) + lambda_i(tau) * y_{i,t-1} + x'_it * beta_i(tau)
+ sum_{l=0}^{pT} z_bar'_{t-l} * delta_{il}(tau) + e_it(tau)

{pstd}
The Mean Group estimator (eq. 2.21): theta_hat(tau) = (1/N) * sum theta_hat_i(tau),
where theta_i = (lambda_i, beta'_i)'.

{pstd}
Long-run effects: theta_j(tau) = beta_j(tau) / (1 - lambda(tau)), with
delta-method standard errors. Half-life: h(tau) = ln(0.5) / ln(|lambda(tau)|).

{pstd}
Inference uses Theorem 4 (heterogeneous coefficients):
V_hat_v = (1/(N-1)) * sum (theta_hat_i - theta_hat)(theta_hat_i - theta_hat)'.


{marker options}{...}
{title:Options}

{dlgtab:Required}

{phang}
{opt tau(numlist)} specifies the quantiles at which estimation is performed.
Values must be between 0 and 1 exclusive.
Example: {cmd:tau(0.1 0.25 0.5 0.75 0.9)} for five quantiles.

{dlgtab:Estimator Selection}

{phang}
{opt qccemg} specifies the Quantile CCE Mean Group estimator. When this
option is given, the {cmd:lr()} option is not required. The model automatically
includes one lag of the dependent variable (y_{i,t-1}) and the independent
variables at their contemporaneous level.

{phang}
{opt qccepmg} specifies the Quantile CCE Pooled Mean Group estimator. This is
the pooled counterpart of QCCEMG, based on Pesaran (2006) CCEP methodology.
The same individual quantile regressions are estimated, but averaging and
inference follow the Pooled Mean Group approach. Cannot be combined with {cmd:qccemg}.

{phang}
{opt lr(varlist)} specifies the long-run level variables for CS-PQARDL.
The first variable must be the lagged dependent variable (e.g., L.y),
which identifies the error correction mechanism. The remaining variables
are the long-run regressors.

{dlgtab:CS-PQARDL Options}

{phang}
{opt pmg} specifies the Pooled Mean Group estimator. This is the default
for CS-PQARDL.

{phang}
{opt mg} specifies the Mean Group estimator.

{phang}
{opt dfe} specifies the Dynamic Fixed Effects estimator.

{phang}
{opt p(#)} specifies the autoregressive lag order. Default is 1.

{phang}
{opt q(numlist)} specifies distributed lag orders for independent variables.
A single number applies to all variables. A per-variable list is also accepted.

{phang}
{opt ecm} uses the error correction model reparameterization for CS-PQARDL.
In this form, CSA enter the ECT only; short-run CSA differences are dropped.

{phang}
{opt lagsel(string)} activates automatic lag selection ({cmd:aic} or {cmd:bic}).

{dlgtab:Cross-Sectional Dependence}

{phang}
{opt cr_lags(#)} sets the number of lags of cross-sectional averages.
Default is floor(T^{1/3}) per Chudik and Pesaran (2015).

{dlgtab:Advanced Analysis}

{phang}
{opt full} requests a comprehensive suite of advanced post-estimation 
analysis tables when multiple quantiles are specified. This includes:
(1) Cross-quantile coefficient comparison
(2) Pairwise quantile differences (z-tests)
(3) Persistence profile across quantiles
(4) Quantile slope homogeneity test (Joint Wald test across quantiles)
(5) For QCCEMG/QCCEPMG only: Long-run effects and Impulse Response Functions (IRF).

{phang}
{opt graph} generates and saves figures visualizing the estimation results 
across quantiles. This includes: coefficient processes (long-run beta(tau), short-run 
impacts, QCCEMG/QCCEPMG theta(tau) and lambda(tau)), ECT heatmaps (for CS-PQARDL), 
and half-life comparisons. Short-run coefficient bounds are graphed utilizing 
MG-averaged variance ({it:sr_V}). {bf:Note:} For CS-PQARDL, ensure short-run 
{it:indepvars} are explicitly differenced (e.g. {cmd:dx1}) to avoid collinearity 
with {cmd:lr()} level variables, which would flatten the short-run graphs to zero.

{dlgtab:Display}

{phang}
{opt showindividual} displays per-panel estimation results.

{phang}
{opt showcsa} displays the coefficients of the Cross-Sectional Averages (CSA).
These are treated as nuisance parameters to absorb unobserved common factors.

{phang}
{opt notable} suppresses the coefficient tables.

{phang}
{opt noconstant} suppresses the constant term.


{marker examples}{...}
{title:Examples}

{pstd}Setup: generate simulated panel data for testing{p_end}

{phang2}{cmd:. clear}{p_end}
{phang2}{cmd:. set seed 12345}{p_end}
{phang2}{cmd:. set obs 50}{p_end}
{phang2}{cmd:. gen id = _n}{p_end}
{phang2}{cmd:. expand 100}{p_end}
{phang2}{cmd:. bysort id: gen t = _n}{p_end}
{phang2}{cmd:. xtset id t}{p_end}
{phang2}{cmd:. gen x1 = rnormal()}{p_end}
{phang2}{cmd:. gen x2 = rnormal()}{p_end}
{phang2}{cmd:. bysort t: egen f = mean(rnormal())}{p_end}
{phang2}{cmd:. gen y = 0.5*L.y + 1.0*x1 + 0.5*x2 + 0.3*f + rnormal() if t > 1}{p_end}
{phang2}{cmd:. gen dy = D.y}{p_end}
{phang2}{cmd:. gen dx1 = D.x1}{p_end}
{phang2}{cmd:. gen dx2 = D.x2}{p_end}

{pstd}{bf:Example 1:} QCCEMG at median{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.5) qccemg}{p_end}

{pstd}{bf:Example 2:} QCCEMG at multiple quantiles{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.25 0.5 0.75) qccemg}{p_end}

{pstd}{bf:Example 3:} CS-PQARDL with long-run specification{p_end}

{phang2}{cmd:. xtcspqardl dy dx1 dx2, lr(L.y x1 x2) tau(0.25 0.5 0.75)}{p_end}

{pstd}{bf:Example 4:} CS-PQARDL with ECM reparameterization{p_end}

{phang2}{cmd:. xtcspqardl dy dx1 dx2, lr(L.y x1 x2) tau(0.5) ecm}{p_end}

{pstd}{bf:Example 5:} QCCEMG with custom CSA lags{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.25 0.5 0.75) qccemg cr_lags(3)}{p_end}

{pstd}{bf:Example 6:} Post-estimation access{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.5) qccemg}{p_end}
{phang2}{cmd:. ereturn list}{p_end}
{phang2}{cmd:. matrix list e(lambda_mg)}{p_end}
{phang2}{cmd:. matrix list e(theta_mg)}{p_end}

{pstd}{bf:Example 7:} QCCEPMG at median{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.5) qccepmg}{p_end}

{pstd}{bf:Example 8:} QCCEPMG at multiple quantiles with CSA display{p_end}

{phang2}{cmd:. xtcspqardl y x1 x2, tau(0.25 0.5 0.75) qccepmg showcsa}{p_end}


{marker results}{...}
{title:Stored results}

{pstd}
{cmd:xtcspqardl} stores the following in {cmd:e()}:

{pstd}{bf:When estimator is QCCEMG or QCCEPMG:}{p_end}

{synoptset 24 tabbed}{...}
{p2col 5 24 28 2: Scalars}{p_end}
{synopt:{cmd:e(N)}}number of observations{p_end}
{synopt:{cmd:e(n_g)}}number of panels{p_end}
{synopt:{cmd:e(valid_panels)}}number of panels successfully estimated{p_end}
{synopt:{cmd:e(k)}}number of independent variables{p_end}
{synopt:{cmd:e(ntau)}}number of quantiles{p_end}
{synopt:{cmd:e(cr_lags)}}number of CSA lags{p_end}
{synopt:{cmd:e(avg_T)}}average time periods per panel{p_end}

{p2col 5 24 28 2: Macros}{p_end}
{synopt:{cmd:e(cmd)}}{cmd:xtcspqardl}{p_end}
{synopt:{cmd:e(estimator)}}{cmd:qccemg} or {cmd:qccepmg}{p_end}
{synopt:{cmd:e(depvar)}}dependent variable name{p_end}
{synopt:{cmd:e(indepvars)}}independent variable names{p_end}

{p2col 5 24 28 2: Matrices}{p_end}
{synopt:{cmd:e(lambda_mg)}}MG autoregressive coefficient lambda(tau){p_end}
{synopt:{cmd:e(lambda_V)}}variance of lambda_mg{p_end}
{synopt:{cmd:e(beta_mg)}}MG contemporaneous coefficients beta(tau){p_end}
{synopt:{cmd:e(beta_V)}}variance-covariance of beta_mg{p_end}
{synopt:{cmd:e(theta_mg)}}MG long-run effects theta_j(tau) = beta_j/(1-lambda){p_end}
{synopt:{cmd:e(halflife_mg)}}MG half-life by quantile{p_end}
{synopt:{cmd:e(lambda_all)}}panel-specific lambda (N x ntau){p_end}
{synopt:{cmd:e(beta_all)}}panel-specific beta (N x k*ntau){p_end}

{pstd}{bf:When estimator is CS-PQARDL:}{p_end}

{synoptset 24 tabbed}{...}
{p2col 5 24 28 2: Scalars}{p_end}
{synopt:{cmd:e(N)}}number of observations{p_end}
{synopt:{cmd:e(n_g)}}number of panels{p_end}
{synopt:{cmd:e(valid_panels)}}panels successfully estimated{p_end}
{synopt:{cmd:e(p)}}AR lag order{p_end}
{synopt:{cmd:e(k)}}number of short-run independent variables{p_end}
{synopt:{cmd:e(k_lr)}}number of long-run regressors{p_end}
{synopt:{cmd:e(ntau)}}number of quantiles{p_end}
{synopt:{cmd:e(cr_lags)}}CSA lag order{p_end}

{p2col 5 24 28 2: Matrices}{p_end}
{synopt:{cmd:e(beta_mg)}}MG long-run cointegrating coefficients{p_end}
{synopt:{cmd:e(beta_V)}}variance of beta_mg{p_end}
{synopt:{cmd:e(rho_mg)}}MG speed of adjustment rho(tau){p_end}
{synopt:{cmd:e(rho_V)}}variance of rho_mg{p_end}
{synopt:{cmd:e(halflife_mg)}}MG half-life{p_end}
{synopt:{cmd:e(phi_mg)}}MG AR lag coefficients{p_end}
{synopt:{cmd:e(sr_mg)}}MG short-run impact coefficients{p_end}
{synopt:{cmd:e(csa_coef_mg)}}MG CSA nuisance coefficients{p_end}
{synopt:{cmd:e(beta_all)}}panel-specific long-run coefficients{p_end}
{synopt:{cmd:e(rho_all)}}panel-specific speed of adjustment{p_end}


{marker references}{...}
{title:References}

{phang}
Harding, M., Lamarche, C., and Pesaran, M.H. (2018).
{it:Common correlated effects estimation of heterogeneous dynamic panel quantile regression models.}
Journal of Applied Econometrics, 35(3), 294-314.
{browse "https://doi.org/10.1002/jae.2753"}
{p_end}

{phang}
Pesaran, M.H. (2006).
{it:Estimation and inference in large heterogeneous panels with a multifactor error structure.}
Econometrica, 74(4), 967-1012.
{p_end}

{phang}
Chudik, A. and Pesaran, M.H. (2015).
{it:Common correlated effects estimation of heterogeneous dynamic panel data models with weakly exogenous regressors.}
Journal of Econometrics, 188(2), 393-420.
{p_end}

{phang}
Cho, J.S., Kim, T., and Shin, Y. (2015).
{it:Quantile cointegration in the autoregressive distributed-lag modeling framework.}
Journal of Econometrics, 188(1), 281-300.
{p_end}

{phang}
Pesaran, M.H., Shin, Y., and Smith, R.P. (1999).
{it:Pooled mean group estimation of dynamic heterogeneous panels.}
Journal of the American Statistical Association, 94(446), 621-634.
{p_end}

{phang}
Pesaran, M.H. and Smith, R.P. (1995).
{it:Estimating long-run relationships from dynamic heterogeneous panels.}
Journal of Econometrics, 68(1), 79-113.
{p_end}

{phang}
Koenker, R. and Bassett, G. (1978).
{it:Regression quantiles.}
Econometrica, 46(1), 33-50.
{p_end}

{phang}
Ul-Durar, S., Bakkar, Y., Arshed, N., Naveed, S., and Zhang, B. (2025).
{it:FinTech and economic readiness: Institutional navigation amid climate risks.}
Research in International Business and Finance, 73, 102543.
{p_end}


{marker requirements}{...}
{title:Requirements}

{pstd}
Stata 15.1 or later.{p_end}


{marker author}{...}
{title:Author}

{pstd}
Dr Merwan Roudane{break}
Email: {browse "mailto:merwanroudane920@gmail.com":merwanroudane920@gmail.com}
{p_end}

{pstd}
Please cite this package as:{break}
Roudane, M. (2026). XTCSPQARDL: Stata module for Cross-Sectionally Augmented
Panel Quantile ARDL and Quantile CCE Mean Group estimation.
{p_end}
