

program stata_sage

    version 10
    syntax [anything] [if],

    * Generating a random number
	
    local ui = floor(120 * runiform() + 1)

    * Defining possible answers 
	
    local answer1 "Results are statistically insignificant."
    local answer2 "Run a regression and find out."
    local answer3 "Check the p-value."
    local answer4 "Results are statistically significant."
    local answer5 "Need more data to answer that."
    local answer6 "Have you tried a chi-square test?"
    local answer7 "Data suggests yes."
    local answer8 "Perform a hypothesis test."
    local answer9 "Time for a data audit."
    local answer10 "Correlation does not imply causation."
    local answer11 "You might need a larger sample size."
    local answer12 "Results may vary."
    local answer13 "Let's bootstrap the data."
    local answer14 "Run a t-test to be sure."
    local answer15 "Model says yes."
    local answer16 "Confidence interval looks good."
    local answer17 "Run a Monte Carlo simulation."
    local answer18 "Try a different model specification."
    local answer19 "Consider using a fixed effects model."
    local answer20 "Look for heteroscedasticity."
    local answer21 "Check for multicollinearity."
    local answer22 "Results are inconclusive."
    local answer23 "More observations needed."
    local answer24 "Outliers might be affecting results."
    local answer25 "Think about potential endogeneity."
    local answer26 "Maybe try a log transformation."
    local answer27 "Results are robust."
    local answer28 "The universe conspires in your favor!"
    local answer29 "Try a different estimation method."
    local answer30 "Have you considered interaction effects?"
    local answer31 "In a parallel universe."
    local answer32 "Check the R-squared value."
    local answer33 "Test for normality."
    local answer34 "Use a larger sample size for better results."
    local answer35 "Data visualization might help."
    local answer36 "You need to account for seasonality."
    local answer37 "Randomized controlled trial might be needed."
    local answer38 "Run a factorial experiment."
    local answer39 "Double-check your coding."
    local answer40 "Revisit your assumptions."
    local answer41 "Cross-validate your model."
    local answer42 "Consult Nick Cox."
    local answer43 "Verify the assumptions."
    local answer44 "Outlier detected."
    local answer45 "Inspect data quality."
    local answer46 "Check the skewness."
    local answer47 "Need to clean the data first."
    local answer48 "Examine the correlation matrix."
    local answer49 "Perform a cross-validation."
    local answer50 "Perform a time series analysis."
    local answer51 "Check the residuals."
    local answer52 "Have you tried turning it off and on again?"
    local answer53 "Check for autocorrelation."
    local answer54 "Time to run a cluster analysis."
    local answer55 "Consider using a hierarchical model."
    local answer56 "Test for stationarity."
    local answer57 "Is there seasonality in the data?"
    local answer58 "Investigate model specification errors."
    local answer59 "Try dimensionality reduction."
    local answer60 "Examine the out-of-sample performance."

    * Non-data specific responses
	
    local answer61 "It is certain."
    local answer62 "Outlook looks good."
    local answer63 "You may rely on it."
    local answer64 "Ask again later."
    local answer65 "Concentrate and ask again."
    local answer66 "Reply hazy, try again."
    local answer67 "My reply is no."
    local answer68 "My sources say no."
    local answer69 "As I see it, yes."
    local answer70 "Better not tell you now."
    local answer71 "Cannot predict now."
    local answer72 "Don't count on it."
    local answer73 "It is decidedly so."
    local answer74 "Most likely."
    local answer75 "Outlook not so good."
    local answer76 "Signs point to yes."
    local answer77 "Very doubtful."
    local answer78 "Without a doubt."
    local answer79 "Yes."
    local answer80 "Yes, definitely."
    local answer81 "You've got to be kidding."
    local answer82 "You wish."
    local answer83 "I don't thnk that I care."
    local answer84 "Meh."
    local answer85 "Hell no!"
    local answer86 "Of course!"
    local answer87 "Maybe in another lifetime."
    local answer88 "It's your day, my friend!"
    local answer89 "Don't bet on it."
    local answer90 "So now you need my help?"
    local answer91 "You call that a question?"
    local answer92 "Better that you don't know."
    local answer93 "The stars say yes!"
    local answer94 "It depends."
    local answer95 "Act now."
    local answer96 "Sure! No harm trying."
    local answer97 "Go for it."
    local answer98 "Wouldn't you like to know?"
    local answer99 "Way out of your league."
    local answer100 "Signs point to yes!"
    local answer101 "Take the leap!"
    local answer102 "Let's dwell on it!"
    local answer103 "No harm dreaming about it!"
    local answer104 "Absolutely."
    local answer105 "You've got to at least try!"
    local answer106 "I don't trust the odds."
    local answer107 "Dwelling on it. Try again to find out."
    local answer108 "Positive."
    local answer109 "Consult me later."
    local answer110 "Sure, if pigs fly."
    local answer111 "Yeah, and I'm the queen of England."
    local answer112 "Do you really need to ask?"
    local answer113 "I wouldn't hold my breath."
    local answer114 "Only if you're really lucky."
    local answer115 "Dream on!"
    local answer116 "Why not? Miracles happen."
    local answer117 "Not in this lifetime."
    local answer118 "Don't make me laugh."
	local answer119 "The answer is 42."
	local answer120 "The fate of the universe depends on things happening this way."

    * Displaying the answer
	
    display as result ""
    display as result "        `answer`ui''"
	
end

