{smcl}
{* *! survcollapse.sthlp}                                                                                                                      
{* *! v1.1 23Feb2026  Leonelo Bautista}                                                                                                 
{cmd:Help for survcollapse}{right:Copy}
{hline}
                                                                                                                                               
{title:Title}
{p 4 4 2}                                                                                                                                      
{hi:survcollapse} {hline 2} Collapses surveillance data over a chosen time unit, and creates flagged observations for missing time units.      
                                                                                                                                               
{title:Syntax}                                                                                                                                 
{p 8 8 2}                                                                                                                                      
{cmd:survcollapse} [{it:if}] [{it:in}], 
{cmd:datevar(}{it:varname}{cmd:)} {cmd:casevar(}{it:varname}{cmd:)} {cmd:timevar(}{it:varname}{cmd:)} {cmd:saving(}{it:filename}{cmd:)} [{cmd:keepvars(}{it:varlist}{cmd:)} {cmd:replace}]
                                                                                                                                               
{title:Description}
{p 4 4 2}
{cmd:survcollapse} collapses surveillance data in which each observation may represent a single case
or multiple cases occurring on the same date ({bf:time unit}), producing totals over a user-selected
coarser time unit (for example, aggregating daily data to weekly or monthly data). It ensures
that the resulting time series is {bf:complete}: observations for time units (e.g., days) that did not 
exist in the original dataset are automatically created and assigned {bf:0} cases. Only gaps between 
the minimum and maximum observed value of {cmd:timevar()} are completed. The flag variable {cmd:created} 
indicates whether a time unit was observed in the original data ({cmd:created} = 0) or was generated by 
{cmd:survcollapse} and assigned 0 cases in the collapsed data ({cmd:created} = 1).

{p 4 4 2}
{cmd:survcollapse} is not a replacement for {helpb collapse}. It aggregates counts using a sum over
{cmd:casevar()} within groups defined by {cmd:keepvars()} and {cmd:timevar()}. In addition, {cmd:survcollapse}
explicitly creates observations for missing time units and assigns them a value of 0 cases, producing a
complete time series, while {helpb collapse} only retains combinations of grouping variables that already 
exist in the data.
                                                                                                                                   
{p 4 4 2}                                                                                                                                      
Grouping (e.g., national, province, region) is controlled by the user through optional {cmd:keepvars()}
and optional {cmd:if}/{cmd:in} qualifiers. {cmd:survcollapse} collapses by the selected {cmd:timevar()}
only; {cmd:keepvars()} is retained as a constant identifier in the output.                                                        
                                                                                                                                               
{title:Options}
{dlgtab:Required}
{p 4 8 2}                                                                                                                                      
{cmd:datevar(}{it:varname}{cmd:)} specifies the least coarse time variable in the dataset (e.g., a Stata daily date)
over which cases are reported. This variable is used as the time reference for generating the selected
{cmd:timevar()} and for completing missing time units.
 
{p 4 8 2}
{cmd:casevar(}{it:varname}{cmd:)} specifies the numeric case-count variable to be summed by {cmd:survcollapse}.                                                        

{p 4 8 2}  
{cmd:timevar(}{it:varname}{cmd:)} specifies the type of time variable that {cmd:survcollapse} will generate
from {cmd:datevar()} and use as the collapsing time unit. Allowed formats are:

{p 8 12 2}
{cmd:__day} daily time unit. This is a numeric Stata daily date variable, with values corresponding
to the number of days since 01jan1960. If the variable {cmd:year} does not exist, it could be created
with {cmd:gen int year = year({it:__day})}.

{p 8 12 2}
{cmd:stata_week} Stata week series (Sunday-based weeks). When this option is used, {cmd:survcollapse}
outputs {cmd:year} and {cmd:week} (week-of-year), Stata's default for weekly time-series analysis.

{p 8 12 2}
{cmd:iso_week} ISO 8601 week series (Monday–Sunday weeks; week 1 is the week containing January 4).
When this option is used, {cmd:survcollapse} outputs ISO-consistent {cmd:year} and {cmd:week}.

{p 8 12 2}
{cmd:cdc_week} CDC/MMWR epidemiologic week series (Sunday–Saturday weeks; week 1 is the first week
with at least four days in January). When this option is used, {cmd:survcollapse} outputs CDC/MMWR-consistent
{cmd:year} and {cmd:week}.
                                                                                                         
{p 4 8 2}                                                                                                                                      
{cmd:saving(}{it:filename}{cmd:)} specifies the user-defined name of the output dataset to be saved.                                                                    
Use {cmd:replace} to overwrite an existing file.                                                                                               

{dlgtab:Optional}
{p 4 8 2}                                                                                                                                      
{cmd:keepvars(}{it:varlist}{cmd:)} specifies identifier variables (e.g., country, province, region, sex/gender, 
age group, case definition, etc.) to be retained in the output dataset. These variables do not define panels 
for collapsing; {cmd:survcollapse} collapses by {cmd:timevar()} only. Therefore, variables in {cmd:keepvars()} 
must be constant within the {it:if}/{it:in} sample. If {cmd:keepvars()} includes a variable whose values vary 
within the selected sample, {cmd:survcollapse} may fail. {cmd:keepvars()} may be omitted and {cmd:survcollapse} 
will still run. However, when subsetting with {it:if}/{it:in}, including the corresponding identifier variable(s) 
in {cmd:keepvars()} ensures they are retained in the output dataset.
                                                           
{p 4 8 2}                                                                                                                                      
{cmd:replace} allows overwriting the file specified in {cmd:saving()}.                                                                          
                                                                                                                                               
{title:Output}                                                                                                                                 
{p 4 4 2}                                                                                                                                      
The saved dataset contains (at minimum) the following variables:

{p 8 12 2}
{it:casevar} summed cases for the user-selected {cmd:timevar()} unit.

{p 8 12 2}
{it:created} indicator for filled-in time units: 1 if the time unit was created by {cmd:survcollapse}, 0 if it existed in the data prior to collapsing.


{p 4 4 2}
Output time variables depend on {cmd:timevar()}:

{p 8 12 2}
If {cmd:timevar(__day)} is used, the output includes {cmd:__day} (daily Stata date).

{p 8 12 2}
If a weekly option is used the output includes {cmd:year} and {cmd:week}, where {cmd:week} follows the selected weekly definition.

{p 4 4 2}
If {cmd:keepvars()} is specified, those variables are included in the output as constants.
                                                                                                                                               
{title:Notes}                                                                                                                                  
{p 4 4 2}                                                                                                                                      
The output dataset is completed over the range [min(time), max(time)] of the selected time unit. Missing
time units are created and assigned 0 cases and flagged with {cmd:created} = 1.

{p 4 4 2}
If collapsing a single national series without a variable corresponding to country, the user should create 
one before running the program (e.g., {cmd:gen byte country = 1}) and then use {cmd:keepvars(country)}.

{p 4 4 2}
If {cmd: set varabbrev off} is in effect, option arguments must use full variable names.
                                                                     
{title:Examples}

{p 4 4 2}
A common use is to convert case-level (line-list) data—often with multiple observations per day—into a 
collapsed daily time series (one observation per day with one or more cases). Case-level data or a 
collapsed daily time series can then be aggregated into weekly or monthly totals. For example, collapse 
to one observation per day (filling missing days between the minimum and maximum observed day) and save 
the resulting dataset:

{p 8 8 2}
{cmd:survcollapse, datevar(date) casevar(cases) timevar(__day) keepvars(country) saving(temp1.dta) replace}

{p 4 4 2}
Aggregate the daily series to ISO epidemiologic weeks and save the weekly dataset:

{p 8 8 2}
{cmd:survcollapse, datevar(__day) casevar(cases) timevar(iso_week) keepvars(country) saving(temp2.dta) replace}

{p 4 4 2}
Collapse data for a single state:

{p 8 8 2}
{cmd:survcollapse if state==1, datevar(date) casevar(cases) timevar(iso_week) keepvars(state) saving(temp_state1_week.dta) replace}

{p 4 4 2}
Collapse laboratory-confirmed cases for a single state:

{p 8 8 2}
{cmd:survcollapse if state==10 & tested==1, datevar(date) casevar(cases) timevar(iso_week) keepvars(state tested) saving(temp_state1_tested1_week.dta) replace}

{p 4 4 2}
To obtain monthly totals, create a month identifier from the daily date and then collapse using that
month variable. Re-collapsing weekly data to months is not recommended because weeks do not align with
calendar months (weeks may overlap two months). For example:

{p 8 8 2}
{cmd:gen month = mofd(__day)}

{p 8 8 2}
{cmd:format month %tm}

{p 8 8 2}
{cmd:survcollapse, datevar(__day) casevar(cases) timevar(month) keepvars(country) saving(temp3.dta) replace}
                                                                                                                                            
{title:Stored results}                                                                                                                         
{p 4 4 2}                                                                                                                                      
None.                                                                                                                                          
                                                                                                                                               
{title:Author}                                                                                                                                 
{p 4 4 2}                                                                                                                                      
Leonelo Bautista{break}
University of Wisconsin-Madison{break}
Department of Population Health Sciences{break}	
lebautista@wisc.edu

{p 4 4 2}
v1.0 17Jan2026{break}
                                                                                                                                               
{title:Also see}
{p 4 4 2}
{help collapse}, {help tsfill}, {help fillin}, {help wofd}, {help yw}
