{smcl}
{* 12Jan2025}{...}
{hi:help geoflow}{...}
{right:{browse "https://github.com/asjadnaqvi/stata-geoflow":geoflow v1.0 (GitHub)}}

{hline}

{title:geoflow}: A Stata module for generating spatial flow arcs.

The package assumes that the users have the following two files:
- {bf:file1}: This file should contain a numeric flow variable defined by {opt from()} and {opt to()} identifiers. The file should already be loaded before using the command.
- {bf:file2}: This file should contain a unique {opt key()} variable, for which coordinates are also defined, and can be merged with {opt from()} and {opt to()} variables.
The coordinates should be in the form {it:_CX} and {it:_CY}. These are generated by default if {opt spshape2dta} is used. 

Basic use is as follows:
- use {bf:file1.dta}, clear
- {opt geoflow numvar} using {ul:file2}, {opt from(var)} {opt to(var)} {opt key(var)} {it:[other geoflow options]}

The command will generate a new file that contains the coordinates for the arcs. How these arcs are plotted depends on the user
and it is outside the scope of this command. See GitHub page for examples.



{marker syntax}{title:Syntax}
{p 8 15 2}

{cmd:geoflow} {it:numvar} {ifin} {using}, {cmdab:f:rom}(varname) {cmdab:t:o}(varname) {cmdab:key}(var) {cmd:saving}(filename) {cmd:[} {cmd:replace} {cmd:cuts}({it:num}) {cmd:top}({it:num}) {cmd:points}({it:num}) {cmd:]} 

{p 4 4 2}

{synoptset 36 tabbed}{...}
{synopthdr}
{synoptline}

{p2coldent : {opt geoflow numvar} using filename, from(var) to(var) key(var)}The command assumes that the data is already loaded with data containing the
{opt from()} and {opt to()} variables. These variables should contain the identifiers that can be merged with the {it:using} data using the
{opt key()} variable.{p_end}

{p2coldent : {opt points(num)}}Number of points to generate for each arc. Default is {opt points(40)}.{p_end}

{p2coldent : {opt save(filename)}}Name of the file that will be saved containing the arc data.{p_end}

{p2coldent : {opt geoframe}}Convert the data to a {stata help geoframe:geoframe}.{p_end}

{p2coldent : {opt replace}}Replace saved files and geoframe.{p_end}

{p2coldent : {opt groups(num)}}Number of quantile groups to generate for the {it:numvar} variable.{p_end}

{p2coldent : {opt top(num)}}Keep the top {opt num()} values from {it:numvar}. This option is recommended if the data contains a very
large number of pairs.{p_end}

{p2coldent : {opt radius(num)}}Radius of the arcs. Default is {opt radius(350)} which fits well for globals maps in WGS84 projection.
Smaller values will result in larger arcs.{p_end}

{p2coldent : {opt mark}}Generates a variable {it:_mark} in the {opt using} file which equals one for each {opt key()} that
matches with {opt from()} and {opt to()} variables.{p_end}


{title:Dependencies}
{stata ssc install graphfunctions, replace}

{title:Examples}
See {browse "https://github.com/asjadnaqvi/stata-geoflow":GitHub} for examples.

{title:Feedback}
Please submit bugs, errors, feature requests on {browse "https://github.com/asjadnaqvi/stata-geoflow/issues":GitHub} by opening a new issue.

{title:Citation guidelines}
See XXXX for the official SSC citation. 
Please note that the GitHub version might be newer than the SSC version.

{title:Package details}
Version      : {bf:geoflow} v1.0
This release : 12 Jan 2025
First release: 12 Jan 2025
Author       : {browse "https://github.com/asjadnaqvi":Asjad Naqvi} (asjadnaqvi@gmail.com)
Repository   : {browse "https://github.com/asjadnaqvi/stata-geoflow":GitHub}
Keywords     : Stata, graph, flow, arcs
License      : {browse "https://opensource.org/licenses/MIT":MIT}


{title:Other visualization packages}
{psee}
    {helpb arcplot}, {helpb alluvial}, {helpb bimap}, {helpb bumparea}, {helpb bumpline}, {helpb circlebar}, {helpb circlepack}, {helpb clipgeo}, {helpb delaunay}, {helpb graphfunctions}, {helpb geoboundary}, {helpb geoflow}, {helpb joyplot}, 
	{helpb marimekko}, {helpb polarspike}, {helpb sankey}, {helpb schemepack}, {helpb spider}, {helpb splinefit}, {helpb streamplot}, {helpb sunburst}, {helpb ternary}, {helpb treecluster}, {helpb treemap}, {helpb trimap}, {helpb waffle}

Visit {browse "https://github.com/asjadnaqvi":GitHub} for further information.


