{smcl}
{* *! version 1.0 27 Jan 2021}{...}
{vieweralsosee "" "--"}{...}
{vieweralsosee "Install command2" "ssc install command2"}{...}
{vieweralsosee "Help command2 (if installed)" "help command2"}{...}
{viewerjumpto "Syntax" "moranplot##syntax"}{...}
{viewerjumpto "Description" "moranplot##description"}{...}
{viewerjumpto "Options" "moranplot##options"}{...}
{viewerjumpto "Remarks" "moranplot##remarks"}{...}
{viewerjumpto "Examples" "moranplot##examples"}{...}
{title:Title}
{phang}
{bf:moranplot} {hline 2} Moran scatterplot

{marker syntax}{...}
{title:Syntax}
{p 8 17 2}
{cmdab:moranplot}
varlist(numeric)
[if]
[{cmd:,}
{it:options}]

{synoptset 20 tabbed}{...}
{synopthdr}
{synoptline}
{syntab:Main}
{synopt:{opt w(name)}} standardized spatial weight matrix{p_end}
{synopt:{opt id(varname)}} individuals identification{p_end}
{synopt:{opt note(numlist)}} note about graph{p_end}
{synopt:{opt mlabel(varname)}} specify marker variables{p_end}
{synoptline}
{p2colreset}{...}
{p 4 6 2}

{marker description}{...}
{title:Description}
{pstd}
{cmd:moranplot} draws Moran scatterplots. Although it is currently possible to 
draw Moran scatterplots using the {help spatlsa} command, but the graphics are not pretty. 
The scatterplots has an ugly black background and cannot be further edited. 
It cannot be published in academic papers. To solve this problem, 
we developed the moranplot command. This command can draw Moran scatterplots of 
multiple variables simultaneously, graphics are standard and pretty. In addition, 
using grss command solves the problem that the current picture will automatically 
cover the previous picture in the drawing process of Stata. 

{marker options}{...}
{title:Options}
{dlgtab:Main}
{phang}
{opt w(name)} must be required. It specifies the name of the spatial weights matrix to be used in the computation of the requested local spatial autocorrelation statistics. This matrix must have been generated by {help spmat}. This option must be entered with a standardized spatial weight matrix, and the extension of the spatial weight matrix must be .spmat. For example, W1.spmat.

{phang}
{opt id(varname)} must be required. It specifies the name of the variable containing the identifier of each location object of analysis.

{phang}
{opt note(numlist)} specifies a note in the bottom left corner of the Moran scatterplots. Only one numeric variable can be entered with this option, typically enter the year variable in this option, but it can also be ignored.

{phang}
{opt mlabel(varname)} requests that - in the Moran scatterplot - locations be represented by an identifier instead of the default graphic symbol. You can enter character variables or numeric variables. For example, id or name.


{marker examples}{...}
{title:Examples}

{p 4 4 2} Using cross-section data: {p_end}
{p 4 4 2}{inp:.} {stata `"use data.dta"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2, w(W1) id(id)"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2, w(W1) id(id) note(2018)"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2, w(W1) id(id) note(2018) mlabel(name)"'}{p_end}

{p 4 4 2} Using panel data: {p_end}
{p 4 4 2}{inp:.} {stata `"use data.dta"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2 if year==2018, w(W1) id(id)"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2 if year==2018, w(W1) id(id) note(2018)"'}{p_end}
{p 4 4 2}{inp:.} {stata `"moranplot y1 x1 y2 if year==2018, w(W1) id(id) note(2018) mlabel(name)"'}{p_end}

{title:Author}

{p 4 4 2}
{cmd:Chen, Zhenhuan}{break}
College of Economics and Management, Northeast Forestry University, China{break}
Email: {browse "mailto:czh2017@nefu.edu.cn":czh2017@nefu.edu.cn}, {browse "mailto:317792209@qq.com":317792209@qq.com}

{title:Reference}

{p 4 4 2}
{cmd:Chen, Z.; Zhu, H.; Zhao,W.; Zhao, M.; Zhang, Y. Spatial Agglomeration of China’s Forest Products Manufacturing Industry: Measurement, Characteristics and Determinants. Forests 2021, 12, 1006. https://doi.org/10.3390/f12081006}{p_end}

{title:See Also}

Related commands:

{help spatlsa} (if installed)
{help splagvar} (if installed)   {stata ssc install splagvar} (to install this command)
