{smcl}
{* *! version 1.0.3 13th September 2021}{...}
{vieweralsosee "" "--"}{...}
{vieweralsosee "Install command2" "ssc install command2"}{...}
{vieweralsosee "Help command2 (if installed)" "help command2"}{...}
{viewerjumpto "Syntax" "moranplot##syntax"}{...}
{viewerjumpto "Description" "moranplot##description"}{...}
{viewerjumpto "Options" "moranplot##options"}{...}
{viewerjumpto "Remarks" "moranplot##remarks"}{...}
{viewerjumpto "Examples" "moranplot##examples"}{...}
{title:Title}
{phang}
{bf:moranplot} {hline 2} Moran scatter plots

{marker syntax}{...}
{title:Syntax}
{p 8 17 2}
{cmdab:moranplot}
varlist(numeric)
[if]
[{cmd:,}
{it:options}]

{synoptset 20 tabbed}{...}
{synopthdr}
{synoptline}
{syntab:Main}
{synopt:{opt w(name)}} standardized spatial weight matrix{p_end}
{synopt:{opt id(varname)}} individuals identification{p_end}
{synopt:{opt note(numlist)}} note about graph{p_end}
{synopt:{opt mlabel(varname)}} specify marker variable{p_end}
{synopt:{opt mlabvp(varname)}} specify label position{p_end}
{synoptline}
{p2colreset}{...}
{p 4 6 2}

{marker description}{...}
{title:Description}
{pstd}
{cmd:moranplot} draws Moran scatter plots. Although it is currently possible to draw Moran scatter plots using the {help spatlsa} command, but the graphics are not pretty.
The scatter plots has an black background and cannot be further edited.
It cannot be published in academic papers. To solve this problem, we developed the moranplot command.
This command can draw Moran scatter plots of multiple variables simultaneously, graphics are standard and pretty. To avoid the {err:"variable w1_000000 not found"} error, please use the new version of spmat.ado (Version 1.0.5, 26Nov2018) developed by Drukker, D. M., H. Peng, I. R. Prucha, and R. Raciborski. For convenience, I have put the relevant code in the ado file. This is the original work by Drukker et al.(2013). Thanks for their excellent contribution!

{marker options}{...}
{title:Options}
{dlgtab:Main}
{phang}
{opt w(name)} must be required. It specifies the name of the spatial weights matrix to be used in the computation of the requested local spatial autocorrelation statistics. This matrix must have been generated by {help spmat}. This option must be entered with a standardized spatial weight matrix, and the extension of the spatial weight matrix must be .spmat. For example, W1.spmat.

{phang}
{opt id(varname)} must be required. It specifies the name of the variable containing the identifier of each location object of analysis.

{phang}
{opt note(numlist)} specifies a note in the bottom left corner of the Moran scatter plots. Only one numeric variable can be entered with this option, typically enter the year variable in this option, but it can also be ignored.

{phang}
{opt mlabel(varname)} requests that - in the Moran scatter plots - locations be represented by an identifier instead of the default graphic symbol. You can enter character variables or numeric variables. For example, id or name.

{phang}
{opt mlabvp(varname)} must be a numeric variable. You can specify the position of the variable with the time scale on the clock. For example, 5 or 12.


{marker examples}{...}
{title:Examples}

{phang}{cmd: Using cross-section data:}{p_end}
{p 4 4 2}{inp:.} {cmd:use moranplot_data.dta, clear}{p_end}
{p 4 4 2}{inp:.} {cmd:moranplot y1 x1 y2 if year==2018, w(W1) id(id)}{p_end}
{p 4 4 2}{inp:.} {cmd:moranplot y1 x1 y2 if year==2018, w(W1) id(id) note(2018)}{p_end}
{p 4 4 2}{inp:.} {cmd:moranplot y1 x1 y2 if year==2018, w(W1) id(id) note(2018) mlabel(name)}{p_end}
{p 4 4 2}{inp:.} {cmd:moranplot y1 if year==2018, w(W1) id(id) note(2018) mlabel(name) mlabvp(pos)}{p_end}

{phang}{cmd: Using panel data:}{p_end}
{p 4 4 2}{inp:.} {cmd:use moranplot_data.dta, clear}{p_end}
{p 4 4 2}{inp:.} {cmd:forvalues time = 2014/2018 {c -(}}{p_end}
{p 6 4 2} {cmd:2.  moranplot y1 x1 y2 if year==`time', w(W1) id(id) note(`time')}{p_end}
{p 6 4 2} {cmd:3.  {c )-}}{p_end}



{title:Author}

{p 4 4 2}
{cmd:Chen, Zhenhuan}{break}
College of Economics and Management, Northeast Forestry University, China{break}
Email: {browse "mailto:czh2017@nefu.edu.cn":czh2017@nefu.edu.cn}, {browse "mailto:317792209@qq.com":317792209@qq.com}

{title:Reference}

{p 4 4 2}
{cmd:[1] Chen Z, Zhu H, Zhao W, Zhao M, Zhang Y. Spatial Agglomeration of China’s Forest Products Manufacturing Industry: Measurement, Characteristics and Determinants. Forests. 2021, 12(8):1006. https://doi.org/10.3390/f12081006.}{p_end}

{p 4 4 2}
{cmd:[2] Drukker D M, Peng H, Prucha I R, et al. Creating and managing spatial-weighting matrices with the spmat command[J]. Stata Journal, 2013,13(2):242-286.}{p_end}


{title:See Also}

Related commands:

{help spatlsa} (if installed)
{help splagvar} (if installed)   {stata ssc install splagvar} (to install this command)
