{smcl}
{* *! version 1.1.1 April 2026}
{viewerjumpto "Syntax" "bimpoisson##syntax"}{...}
{viewerjumpto "Description" "bimpoisson##description"}{...}
{viewerjumpto "Options" "bimpoisson##options"}{...}
{viewerjumpto "Remarks" "bimpoisson##remarks"}{...}
{viewerjumpto "Examples" "bimpoisson##examples"}{...}
{viewerjumpto "Stored Results" "bimpoisson##stored_results"}{...}
{viewerjumpto "Authors" "bimpoisson##authors"}{...}
{viewerjumpto "References" "bimpoisson##references"}{...}
{viewerjumpto "Acknowledgements" "bimpoisson##acknowledgements"}{...}
{viewerjumpto "Also see" "bimpoisson##alsosee"}{...}

{title:Bivariate mixed Poisson regression (using Maximum Simulated Likelihood)}

{phang}
{cmd:bimpoisson} {hline 2} Bivariate mixed Poisson regression (MSL)

{marker syntax}{...}
{title:Syntax}

{p 8 17 2}
{cmd:bimpoisson}
{it:{help depvar:depvar1}} {it:{help depvar:depvar2}}
[{indepvars}]
{ifin}
[{it:{help weight}}]{cmd:,} 
[{it:{help options}}]

{p 4 4 2}can be used when {it:indepvars} is a common set of predictors 
for each dependent variable. For this case, and also situations where the sets
of predictors for each dependent variable differ, the following syntax can be
used:

{p 8 17 2}
{cmd:bimpoisson}
{it:equation1} {it:equation2}
{ifin}
[{it:{help weight}}]{cmd:,} 
[{it:{help options}}]

{p 4 4 2}where {it:equation1} and {it:equation2} are each specified as

{p 12 12 2}{cmd:(} [{it:eqname}{cmd::}] {it:{help depvar}} [{cmd:=}] [{indepvars}] {cmd:)}
		
{p 4 4 2}{cmd:bimpoisson} shares the features of all estimation commands; see help
{help est}.

{p 4 4 2}{cmd:bimpoisson} typed without arguments redisplays the last estimates. 

{synoptset 20 tabbed}{...}
{synopthdr}
{synoptline}
{syntab:Main}
{synopt :{opt nsim(#)}}number of simulations (default value is 10){p_end}
{synopt :{opt anti:thetic}}use antithetic acceleration{p_end}
{synopt :{opt ha:lton}}use Halton draws (default is standard uniform pseudorandom draws){p_end}
{synopt :{opt burn(#)}}drop # initial elements when creating the Halton sequences (default is 5){p_end}
{synopt :{opt bias}}use first-order bias correction{p_end}
{synopt :{opt seed(#)}}set the seed (relevant if using standard uniform pseudorandom draws){p_end}
{synopt :{opt rho_sf(#)}}set the sampling function correlation (default value is 0){p_end}
{synopt :{opt alt}}use alternative MSL estimation method (default uses sampling function){p_end}
{synopt :{opt rng0}}set the rng state back to its initial value{p_end} 
{syntab:Model}
{synopt :{opt nocons:tant}}suppress constant term{p_end}
{synopt :{opth offset1(varname)}}offset variable for first equation{p_end}
{synopt :{opth offset2(varname)}}offset variable for second equation{p_end}
{synopt :{cmdab:const:raints(}{it:{help constraints():constraints}}{cmd:)}}apply specified linear constraints{p_end}
{syntab:SE/Robust}
{synopt :{opth vce(vcetype)}}{it:vcetype} may be {opt oim},
{opt r:obust}, {opt cl:uster} {it:clustvar}, {opt opg},
{opt boot:strap}, or {opt jack:knife}{p_end}
{syntab:Reporting}
{synopt :{opt irr}}report incidence rate ratios{p_end}
{synopt :{opt ef:orm}}report exponentiated coefficients{p_end}
{synopt :{opt l:evel(#)}}set confidence level; default is {cmd:level(95)}{p_end}
{synopt :{opt nocnsr:eport}}do not display constraints{p_end}
{synopt :{it:{help bimpoisson##display_options:display_options}}}control
INCLUDE help shortdes-displayoptall
{syntab:Maximization}
{synopt :{it:{help bimpoisson##maximize_options:maximize_options}}}control the maximization process; seldom used{p_end}
{synopt:{opt col:linear}}keep collinear variables{p_end}
INCLUDE help shortdes-coeflegend
{synoptline}
{p2colreset}{...}
{p 4 4 2}

INCLUDE help fvvarlist
{p 4 6 2}{it:depvar1}, {it:depvar2}, {it:indepvars}, and {it:depvar} may 
contain time-series operators; see {help tsvarlist}.{p_end}
{p 4 6 2}{opt by} and {opt collect} are allowed; see {help prefix}.{p_end}
{p 4 6 2}{opt pweight}s, {opt fweight}s, {opt aweight}s, and {opt iweight}s 
are allowed; see {help weight}.{p_end}
{p 4 6 2}See {help bimpoisson postestimation} for features available after
estimation.{p_end}

{marker description}{...}
{title:Description}

{p 4 4 2}
{cmd:bimpoisson} fits bivariate mixed Poisson regression models by the method
of maximum simulated likelihood (MSL), following the approaches proposed by 
Munkin and Trivedi (1999). To quote Munkin and Trivedi (`MT'), p. 35,  
"[w]e wish to to specify a general bivariate count model in which 
overdispersion comes through bivariate unobserved heterogeneity which affects 
the conditional mean functions. Assume that the two count variables 
{it:y}1 and {it:y}2 have a Poisson distribution conditional on 
the σ-fields generated by the random variables of unobserved heterogeneity 
{it:ε}1, {it:ε}2 and the set of independent explanatory variables {it:x}1 
and {it:x}2:

{center:{it:yj} | {it:xj}, {it:εj} ~ P({it:μj}), {it:μj} > O, {it:j} = l, 2,}

{p 4 4 2}
where we parameterize the mean parameters {it:μ}1 and {it:μ}2 as
exp({it:x}1'{it:ß}1 + {it:ε}1) and exp({it:x}2'{it:ß}2 + {it:ε}2), 
respectively. The unobservable variables {it:ε}1 and {it:ε}2 are 
assumed jointly normally distributed, i.e. 

{center:({it:ε}1, {it:ε}2) ~ N{(0, 0), ({it:σ}1^2, {it:ρσ}1{it:σ}2, {it:σ}2^2)}, 0 <= |ρ| <= 1."}

{p 4 4 2}
MT recommend using a robust variance estimator.

{p 4 4 2}
For an overview of alternative approaches to modelling bivariate count
data, and software, see Xu and Hardin (2016).
	
{p 4 4 2}
The default MSL estimator implemented in {cmd:bimpoisson} is that described 
by MT, p. 36, in which an importance sampling function is used to address 
the issue that maximization of the MSL function is problematic for values 
of |{it:ρ}| close to one. (Symptoms may include continuous "(backed up)"
messages in the iteration log or "r(430) convergence not achieved".) MT 
use a bivariate standard normal distribution with {it:ρ} = 0 as their 
sampling function. Like Jumamyradov and Munkin (2022), we use a sampling 
distribution that is bivariate normal with means zero, but with 
standard deviations unrestricted. With this approach, drawn values provide more 
effective coverage and improve MSL's estimation of the double integral 
that specifies the bivariate density of the bivariate mixed Poisson model. 
{cmd:bimpoisson} builds on this idea and also allows users to optionally set
a non-zero value for the sampling function correlation using the 
{cmd:rho_sf(#)} option. 

{p 4 4 2}
MT's MSL estimator not taking account of the maximization feasibility issue, 
described in their eq. (11), p. 35, is implemented by selecting 
{cmd:bimpoisson}'s {cmd:alt} option. 

{p 4 4 2} 
By default and following MT, {cmd:bimpoisson}'s two MSL estimators use 
pseudorandom numbers (draws from the standard uniform distribution) when 
simulating probabilities. Optionally, Halton draws can be used instead. 
(Jumamyradov and Munkin (2022) use Halton draws.) According to Train,
"[t]he superior coverage and the negative correlation over observations that 
are obtained with Halton draws combine to make Halton draws far more 
effective than random [uniform] draws for simulation" (2003, p. 231). Train
also states that "[d]iscarding the initial part of the sequence eliminates the 
correlation [between the initial terms of two Halton sequences]. The number of
initial elements to discard needs to be at least as large as the largest
prime that is used in creating the sequences (2003, p. 230)". By default,
{cmd:burn(#)} uses # = 5, noting that our sequences are created using the
first two primes (2, 3).

{p 4 4 2}
The default number of simulations is 10. This is a very low value and should
only be used for checking syntax. For serious modelling, the number of 
simulations is likely to be much larger. We recommend that users, having 
fitted a model with some specific number of simulations, increase the number 
systematically to check that estimates of the mixture distribution parameters 
in particular are robust. 

{p 4 4 2}
Antithetic acceleration is a variance reduction technique according to 
which negatively correlated draws are used instead of independently 
distributed random numbers. We follow MT (section 4.3, pp. 38-39) and 
create one antithetic draw for each draw by reversing the sign of both 
of the two elements. To implement antithetic acceleration, use the 
{cmd:antithetic} option. Antithetic acceleration is commonly used in 
conjunction with standard uniform draws. (It is almost never used together
with Halton draws.) 

{p 4 4 2}
MT (section 4.2, pp. 37-38) also implement a first-order method for correcting 
asymptotic bias in the MSL estimator. To implement this method, use the 
{cmd:bias} option. 

{p 4 4 2}
On the basis of their Monte-Carlo analysis of the MSL estimator using the
sampling function approach, MT (p. 40) report that "[t]he first-order 
correction of the asymptotic bias significantly reduces the number of 
simulations needed for the estimation up a given degree of bias. 
First-order corrected SML together with antithetic sampling produces 
most efficient estimates." Jumamyradov and Munkin (2022) provide more 
extensive analysis of potential bias, and how it varies with the true values
of the mixture distribution parameters.
	
{marker options}{...}
{title:Options}
{dlgtab:Main}

{phang}
{opt nsim(#)} sets number of simulations (default value is 10). 
Unless checking syntax, users should normally specify a much 
larger number{p_end}  
{phang}
{opt anti:thetic} uses antithetic acceleration, as described above.   
Given nsims({it:#}), the total number of simulations is 2{it:#} if 
this option is specified{p_end}   
{phang}
{opt ha:lton} uses Halton draws for simulation rather than the default which is 
standard uniform random draws{p_end}  
{phang}
{opt burn(#)} drop # initial elements when creating the Halton sequences 
(default is 5){p_end}  
{phang}
{opt bias} uses the first-order bias correction, as described above, and is 
recommended{p_end}   
{phang}
{opt seed(str)} sets the seed. Relevant only when using uniform draws. In this
case, users are recommended to set the seed for reproducibility. If no seed 
is set, the current rng state is used{p_end} 
{phang}
{opt rho_sf(#)} sets the sampling function correlation (default # = 0){p_end} 
{phang}
{opt alt} uses the alternative MSL estimation method (default uses sampling 
function{p_end} 
{phang}
{opt rng0} sets the random number generator (`rng') state back to its 
pre-estimation value: see {help rngstate}{p_end}  
{phang}

{dlgtab:Model}

{phang}
{opt noconstant}; see
{helpb estimation options##noconstant:[R] Estimation options}.

{phang}
{opth offset1(varname)}, {opt offset2(varname)},
{opt constraints(constraints)}; see
{helpb estimation options:[R] Estimation options}.

{dlgtab:SE/Robust}

INCLUDE help vce_asymptall

{dlgtab:Reporting}

{phang}
{opt level(#)}, {opt nocnsreport}; see
     {helpb estimation options:[R] Estimation options}.

INCLUDE help displayopts_list

{marker maximize_options}{...}
{dlgtab:Maximization}

{phang}
{it:maximize_options}: {opt dif:ficult},
{opth tech:nique(maximize##algorithm_spec:algorithm_spec)},
{opt iter:ate(#)}, [{cmd:no}]{opt log}, {opt tr:ace},
{opt grad:ient}, {opt showstep}, {opt hess:ian},
{opt showtol:erance}, {opt tol:erance(#)}, {opt ltol:erance(#)}, 
{opt nrtol:erance(#)}, {opt nonrtol:erance}, and
{opt from(init_specs)}; see {helpb maximize:[R] Maximize}.
These options are seldom used.

{pmore}
Setting the optimization type to {cmd:technique(bhhh)} resets the default
{it:vcetype} to {cmd:vce(opg)}.

{phang}
{opt collinear}, {opt coeflegend}; see {helpb estimation options:[R] Estimation options}.


{marker examples}{...}
{title:Examples}

{p 4 4 2}
The examples below are based on the data about numbers of doctor and hospital
visits and their predictors accompanying the {cmd:bivcnto} package 
by Xu and Hardin (2016). The data are downloadable via the commands {stata "net sj 16-2 st0433"} and
{stata "net get st0433"}. MT's empirical application is based on data previously
 used by Deb and Trivedi (1997): see "debtrivedi.dta". (We downloaded these 
 data from the {it: Journal of Applied Econometrics} archive website 
 and converted them to Stata format.)

{p 4 8 2}{cmd: use "rwm1984.dta", clear}

{p 4 8 2}{cmd: correlate docvis hospvis}

{p 4 8 2}{cmd: generate byte postHS = edlevel1 == 0}

{p 4 8 2}{cmd: generate byte MarM = (married == 1 & female == 0)}

{p 4 8 2}{cmd: generate byte MarF = (married == 1 & female == 1)}

{p 4 8 2}{cmd: generate byte SinM = (married == 0 & female == 0)}

{p 4 8 2}{cmd: generate byte SinF = (married == 0 & female == 1)}

{p 4 8 2}{cmd: global xvars MarM SinM SinF kids outwork postHS}

{p 4 8 2}{cmd: * 400 uniform draws & antithetics, bias correction}

{p 4 8 2}{cmd: bimpoisson docvis hospvis $xvars, robust ///}

{p 8 8 2}{cmd: seed(13159) nsim(400) bias antithetic}	

{p 4 8 2}{cmd: matrix b1 = e(b) }

{p 4 8 2}{cmd: * increase # sims (800)}

{p 4 8 2}{cmd: bimpoisson docvis hospvis $xvars, robust ///}

{p 8 8 2}{cmd: seed(4321) from(b1) nsim(800) bias antithetic}

{p 4 8 2}{cmd: * same again, but with Halton draws}

{p 4 8 2}{cmd: bimpoisson docvis hospvis $xvars, robust halton ///}

{p 8 8 2}{cmd: from(b1) nsim(800) bias} 

{p 4 8 2}{cmd: * alternative approach (not using sampling function)}

{p 4 8 2}{cmd: bimpoisson docvis hospvis $xvars, robust halton alt ///}

{p 8 8 2}{cmd: nsim(400) bias}

{marker stored_results}{...}
{title:Stored results}

{p 4 4 2} In addition to the usual results saved after {cmd:ml},
{cmd:bimpoisson} also saves the following in e():

{p2col 5 15 19 2: Scalars}{p_end}
{synoptset 15 tabbed}{...}
{synopt:{cmd:e(nsims)}} number of simulations used to calculate the
simulated log-likelihood{p_end}
{synopt:{cmd:e(sigma1)}} estimate of sigma1{p_end}
{synopt:{cmd:e(sigma1_se)}} estimate of the standard error of sigma1{p_end}
{synopt:{cmd:e(sigma2)}} estimate of sigma1{p_end}
{synopt:{cmd:e(sigma2_se)}} estimate of the standard error of sigma2{p_end}
{synopt:{cmd:e(rho)}} estimate of rho{p_end}
{synopt:{cmd:e(rho_se)}} estimate of the standard error of rho{p_end}
{synopt:{cmd:e(antithetic)}} 1 if {cmd:antithetic} option used, 0 otherwise{p_end}
{synopt:{cmd:e(halton)}} 1 if {cmd:halton} option used, 0 otherwise{p_end}
{synopt:{cmd:e(burn)}} value of # set by {cmd:burn(#)} option{p_end}
{synopt:{cmd:e(bias)}} 1 if {cmd:bias} option used, 0 otherwise{p_end}
{synopt:{cmd:e(rho_sf)}} value of # set by {cmd:rho_sf(#)} option{p_end}
{synopt:{cmd:e(rng0)}} 1 if {cmd:rng0} option used; 0 otherwise{p_end}

{p2col 5 15 19 2: Macros}{p_end}
{synoptset 15 tabbed}{...}
{synopt:{cmd:e(seed)}} contains the seed set by the {cmd:seed} option if 
specified. If seed not set, contains "seed not set"{p_end}

{marker authors}{...}
{title:Authors}
{p}

{p 4 4 2}Stephen P. Jenkins <s.jenkins@lse.ac.uk>{break}
London School of Economics and Political Science (LSE)

{p 4 4 2}Fernando Rios-Avila <f.rios.a@gmail.com>{break}
London School of Economics and Political Science (LSE)

{marker references}{...}
{title:References}

{p 4 8 2}
Deb, P. and Trivedi, P. K. 1997. Demand for medical care by the elderly: 
a finite mixture approach. {it:Journal of Applied Econometrics} 12, 313{c -}336.
{browse "https://doi.org/10.1002/(SICI)1099-1255(199705)12:3%3C313::AID-JAE440%3E3.0.CO;2-G"}

{p 4 8 2} Jumamyradov, M. and Munkin, M. K. 2022. Biases in maximum simulated 
likelihood estimation of bivariate models. {it:Journal of Econometric Methods} 
11, 55{c -}70. {browse "https://doi.org/10.1515/jem-2021-0003"}

{p 4 8 2}
Munkin, M. K. and Trivedi, P. K. 1999. Simulated maximum likelihood estimation of multivariate mixed-Poisson regression
models, with application. {it:The Econometrics Journal} 2, 29{c -}48.
{browse "https://doi.org/10.1111/1368-423X.00019"}

{p 4 8 2}
Train, K. E. 2003. {it:Discrete Choice Methods with Simulation}.
Cambridge: Cambridge University Press.
{browse "https://doi.org/10.1017/CBO9780511753930"}

{p 4 8 2}
Xu, X. and Hardin, J. W. 2016. Regression models for bivariate count outcomes.
{it:The Stata Journal} 2, 301{c -}315.
{browse "https://doi.org/10.1177/1536867X1601600203"}

{marker acknowledgements}{...}
{title:Acknowledgements}

{p 4 4 2}
The syntax parsing code for {cmd: bimpoisson} borrows heavily from that 
accompanying {help biprobit}, and this help file is modelled on the help 
file for {help biprobit}.

{marker alsosee}{...}
{title:Also see}

{p 4 4 2}
{help poisson}, {help bivcnto} if installed ({browse "net sj 16-2 st0433"}),
{help ppml} if installed ({browse "net sj 11-2 st0225"}), 
{help ppmlhdfe} if installed ({browse "net sj 20-1 st0589"}) 



