/*
===============================================================================
  profile.do — User startup file
  Generated by editprofile.ado on 17 Jun 2026
  Author:  Wu Lianghai (agd2010@yeah.net)
  School of Business, Anhui University of Technology (AHUT)
  Ma'anshan, China
===============================================================================
  Stata executes profile.do automatically at startup.
  Uncomment and modify the lines below to customise your environment.
===============================================================================
*/

* ---- (1) Default working directory ----
* cd "C:/Users/"

* ---- (2) Graphics scheme ----
* set scheme s2color

* ---- (3) Memory allocation (Stata/MP or SE) ----
* set max_memory 2g

* ---- (4) Variable-value label length ----
* set maxvar 32767

* ---- (5) Matrices size ----
* set matsize 800

* ---- (6) Scrollback buffer ----
* set scrollbufsize 500000

* ---- (7) Additional ado directories ----
* adopath ++ "C:/ado/personal"

* ---- (8) Load favourite packages ----
* cap which estout
* cap which outreg2
* cap which distinct

* ---- (9) Set default log type ----
* set logtype text

* ---- (10) Quietly confirm startup ----
display as txt "(profile.do loaded)"
