{smcl}
{* *! version 2.1.0  07Sep2026}{...}
{* *! version 2.0.0  29May2026}{...}
{* *! version 1.1.0  28Oct2016}{...}
{* *! version 1.0.0  21Aug2016}{...}
{cmd:help pstrata}
{hline}

{title:Title}

{p2colset 5 17 18 2}{...}
{p2col :{hi:pstrata} {hline 2}}Optimal propensity score stratification {p_end}
{p2colreset}{...}


{title:Syntax}

{p 8 17 2}
		{cmd:pstrata} {it:{help varname:treat}} {ifin}
		{cmd:,}
		{opt ps:core}({it:{help varlist:varlist}})
		[ {opt smd:level(#)}
		{opt smi:n(#)}
		{opt sma:x(#)}
		{opt com:mon}
		{opt repl:ace}
		{opt pre:fix}({it:string})
		{opt disp:lay}
		]


{p 4 4 2}
{it:{help varname: treat}} must contain integer values representing the treatment levels


{synoptset 19 tabbed}{...}
{synopthdr}
{synoptline}
{p2coldent:* {opt ps:core}{cmd:(}{it:{help varlist:varlist}}{cmd:)}}One or more propensity scores must be provided, depending on the number of treatment levels{p_end}
{synopt:{opt smd:level}{cmd:(#}{cmd:)}}maximum pairwise standardized mean difference (SMD) allowed within a stratum for it to be considered balanced; default is {cmd:0.25}{p_end}
{synopt:{opt smi:n}{cmd:(#}{cmd:)}}number of quantiles to start with; default is {cmd:0}{p_end}
{synopt:{opt sma:x}{cmd:(#}{cmd:)}}maximum number of strata; default is {cmd:50}{p_end}
{synopt:{opt com:mon}}use only those observations within the region of common support when generating strata {p_end}
{synopt:{opt repl:ace}}replace the strata variables created by {cmd:pstrata} if they already exist{p_end}
{synopt:{opt pre:fix}}adds a prefix to the names of the strata variables created by {cmd:pstrata}; default name is {it:strata1}, {it:strata2}, etc. {p_end}
{synopt:{opt disp:lay}}display a table of the maximum pairwise SMD by stratum for each propensity score, along with an indicator of whether balance was achieved{p_end}
{synoptline}
{p 4 6 2}* {opt pscore()} is required. {p_end}
{p2colreset}{...}

{p 4 6 2}

{title:Description}

{pstd}
{opt pstrata} stratifies the propensity score into strata (quantile-based bins) chosen so that, within each stratum, the treatment groups are balanced on the
propensity score. In general, stratification (also referred to as {it:subclassification}) allows the investigator to analyze outcomes between treatment groups
within each stratum as well as to observe overall differences between groups across all strata (Linden & Adams 2008). It has been shown that stratification
of the propensity score into five quantiles can remove over 90% of the initial bias due to the covariates used to create the propensity score (Cochran 1968;
Rosenbaum & Rubin 1984). While the strata generated by {opt pstrata} can be used in any subsequent analysis, it was specifically intended for use in conjunction
with {help mmws}; which can be downloaded from {help ssc:SSC}.

{pstd}
Before using {opt pstrata}, the propensity score for a given treatment must be estimated. A logit or probit regression model can be used for estimating the propensity score
for a binary treatment and a multinomial logistic or probit regression can be used for estimating propensity scores for multiple treatment levels. {opt pstrata} then generates
one or more strata variables (named {it:strata1}, {it:strata2}, etc.), depending on the number of treatment groups in the study.


{title:Remarks}

{pstd}
{opt pstrata} starts by partitioning the propensity score into {opt smin()} equal-frequency quantiles with {help xtile}. Each of these regions is then
refined one at a time until every region resolves into one of four outcomes:

{pstd}
(1) {bf:accepted} {hline 2} every treatment level is present in the strata, and the maximum pairwise standardized mean
difference (SMD) of the propensity score is below {opt smdlevel()};

{pstd}
(2) {bf:accepted}, but flagged {hline 2} the SMD criterion did not pass, but the strata's own thinnest present treatment level is already
too small to split further reliably, or the ceiling on total strata ({opt smax()}) was reached; the region is kept rather than discarded, 
but marked distinctly from a clean pass so the user can see how many strata truly cleared the balance bar versus ran out of room to keep splitting;

{pstd}
(3) {bf:excluded} {hline 2} the strata is missing at least one treatment level entirely, which no amount of splitting can ever fix (a positivity problem, not
a resolution problem). This is the only outcome that discards observations: the strata variable is left missing for observations in an excluded strata; or

{pstd}
(4) {bf:split} into two new sub-strata (again via {opt xtile}, applied only to this strata's own observations).

{pstd}
Balance is judged with a standardized mean difference. Within a candidate strata, the pscore's mean and variance are
computed separately for each treatment level present, and the worst pairwise SMD across all pairs is compared against a fixed threshold, {opt smdlevel()}
(default {cmd:0.25}, the Rubin (2001) convention; {cmd:0.10} is a common, stricter alternative). Because the threshold is a fixed magnitude, it does not 
get mechanically easier or harder to satisfy as more strata or more treatment-group pairs are checked, so no multiplicity adjustment is needed.

{pstd}
When the study involves multiple treatment levels (groups), this refinement proceeds independently for each respective propensity score.

{pstd}
It is important to note that balance on the propensity score does not ensure that balance has been achieved on the underlying covariates. Thus, after implementing {opt pstrata},
balance should be tested on the covariates underlying each propensity score, and within each strata using {help covbal}; downloadable from {help ssc:SSC}. If
covariate balance has not been achieved, or if balance on the propensity score itself has not achieved, the propensity score(s) should be re-estimated using additional
covariates (if available) as well as interactions between covariates and polynomials of continuous variables. At least in theory, a well estimated propensity score should accurately
represent the underlying covariates.


{title:Options}

{phang}
{opth pscore(varlist)} {cmd:required.} For binary or ordinal level treatments, one propensity score must
be provided. For multiple nominal level treatments, one propensity score must be provided for {it:each} treatment level and they must be
ordered correspondingly (e.g. ps1 ps2 ps3 correspond to treatment levels 0 1 2, respectively).{p_end}

{phang}
{opt smd:level(#)} indicates the maximum pairwise standardized mean difference (SMD) of the propensity score, across every pair of treatment groups present in a
region, allowed before that region is considered balanced; the default is {cmd:0.25} (Rubin 2001).{p_end}

{phang}
{opth smin(#)} indicates the minimum number of quantiles that {opt pstrata} will start with; the default is {cmd:0}.{p_end}

{phang}
{opth smax(#)} indicates the maximum number of strata, accepted plus excluded, that {opt pstrata} will generate by splitting; the default is {cmd:50}.{p_end}

{phang}
{opt common} restricts generation of strata to those observations within the region of common support.{p_end}

{phang}
{opt replace} replaces the strata variables created by {cmd:pstrata} if they already exist. If {cmd:prefix()} is specified, only the strata variables created by {cmd:pstrata} with
the same prefix will be replaced.{p_end}

{phang}
{opt prefix(string)} adds a prefix to the names of the strata variables created by {cmd:pstrata}. Short prefixes are recommended.{p_end}

{phang}
{opt display} displays a table of the maximum pairwise SMD by stratum for each propensity score, along with an indicator of whether balance was achieved
(based on {opt smdlevel()}, shown in the table header). This provides a convenient summary of the stratification results without needing to inspect the
returned matrices directly.{p_end}


{title:Examples}

{pstd}Load example data{p_end}
{p 4 8 2}{stata "webuse cattaneo2, clear":. webuse cattaneo2, clear}{p_end}

{pstd}
{opt (1) Binary treatment:}{p_end}

{pstd}Estimate propensity score for the binary treatment {cmd:mbsmoke} and use {opt pstrata} to generate strata with the default settings{p_end}
{p 4 8 2}{stata "logit mbsmoke mmarried mage c.mage#c.mage fbaby medu":. logit mbsmoke mmarried c.mage##c.mage fbaby medu}{p_end}
{p 4 8 2}{stata "predict pscore, pr":. predict pscore, pr}{p_end}
{p 4 8 2}{stata "pstrata mbsmoke, ps(pscore)":. pstrata mbsmoke, ps(pscore)}{p_end}

{pstd}Review the max pairwise SMD estimated for each stratum{p_end}
{p 4 8 2}{stata "matrix list r(smd1)":. matrix list r(smd1)}{p_end}

{pstd}Use the strata variable generated by {opt pstrata} to generate {helpb mmws} weights{p_end}
{p 4 8 2}{stata "mmws mbsmoke, pscore(pscore) strata(strata1)":. mmws mbsmoke, pscore(pscore) strata(strata1)}{p_end}

{pstd}Examine covariate balance, within strata, with {helpb covbal} using the weights generated in the previous run {p_end}
{p 4 8 2}{stata "bys strata1: covbal mbsmoke pscore mmarried mage fbaby medu, abs for(%9.3f) wt( _mmws)":. bys strata1: covbal mbsmoke pscore mmarried mage fbaby medu, abs for(%9.3f) wt( _mmws)}{p_end}

{pstd}Estimate average treatment effects of {cmd:mbsmoke} on {cmd:bweight} using MMWS weights generated in the previous run {p_end}
{p 4 8 2}{stata "regress bweight mbsmoke [pw=_mmws], robust":. regress bweight mbsmoke [pw=_mmws], robust}{p_end}


{pstd}
{opt (3) Multiple treatments:}{p_end}

{pstd}Load example data{p_end}
{p 4 8 2}{stata "webuse cattaneo2, clear":. webuse cattaneo2, clear}{p_end}

{pstd}Estimate propensity scores for the four treatment levels of {cmd:msmoke} and generate four strata variables corresponding to each treatment, respectively. {p_end}
{p 4 8 2}{stata "mlogit msmoke mage medu fage fedu c.mage#c.mage c.mage#c.medu c.mage#c.fage c.mage#c.fedu c.medu#c.medu, base(0)":. mlogit msmoke mage medu fage fedu c.mage#c.mage c.mage#c.medu c.mage#c.fage c.mage#c.fedu c.medu#c.medu, base(0)}{p_end}

{p 4 8 2}{stata "predict double (ps1 ps2 ps3 ps4), pr":. predict double (ps1 ps2 ps3 ps4), pr}{p_end}
{p 4 8 2}{stata "pstrata msmoke, ps(ps1 ps2 ps3 ps4)":. pstrata msmoke, ps(ps1 ps2 ps3 ps4)}{p_end}


{pstd}Generate weights for nominal treatments using the strata variable created in the previous step {p_end}
{p 4 8 2}{stata "mmws msmoke, pscore(ps1 ps2 ps3 ps4) nominal strata(strata1 strata2 strata3 strata4)":. mmws msmoke, pscore(ps1 ps2 ps3 ps4) nominal strata(strata1 strata2 strata3 strata4)}{p_end}

{pstd}Estimate average treatment effect of each level of {cmd:msmoke} on {cmd:bweight} using MMWS weights generated in the previous run {p_end}
{p 4 8 2}{stata "regress bweight i.msmoke [pw=_mmws], robust":. regress bweight i.msmoke [pw=_mmws], robust}{p_end}

{pstd}Run margins to get reweighted mean {cmd:bweight} for each level of {cmd:msmoke}{p_end}
{p 4 8 2}{stata "margins msmoke":. margins msmoke}{p_end}

{pstd}Run marginsplot to visually display reweighted mean {cmd:bweight} for each level of {cmd:msmoke}{p_end}
{p 4 8 2} {stata "marginsplot,  plotopts(connect(i))": . marginsplot,  plotopts(connect(i))}{p_end}

{pstd}Run pairwise comparisons between reweighted treatment levels, with Bonferroni adjustment for multiple tests  {p_end}
{p 4 8 2}{stata "margins msmoke, pwcompare(effects) mcompare(bonferroni)":. margins msmoke, pwcompare(effects) mcompare(bonferroni)}{p_end}


{marker results}{title:Saved results}

{p 4 8 2}
By default, {cmd:pstrata} stores the following in {cmd:r()}.

{synoptset 17 tabbed}{...}
{p2col 5 15 19 2: Scalars}{p_end}
{synopt:{cmd:r(suppmin)}}the minimum value of common support (will have a suffix for multiple treatments){p_end}
{synopt:{cmd:r(suppmax)}}the maximum value of common support (will have a suffix for multiple treatments){p_end}
{synopt:{cmd:r(minlevN)}}the number of observations belonging to the rarest treatment level in the analytic sample{p_end}
{synopt:{cmd:r(minlevshare)}}the share of the analytic sample belonging to the rarest treatment level{p_end}
{synopt:{cmd:r(minsize)}}the internal per-group minimum-size floor used when deciding whether to split a region further, auto-derived from {opt smdlevel()}{p_end}
{synopt:{cmd:r(sminused)}}the {opt smin()} value actually used (as specified, or auto-derived){p_end}
{synopt:{cmd:r(nstrata}{it:n}{cmd:)}}the number of strata accepted (cleanly or floor-forced) for propensity score {it:n}{p_end}
{synopt:{cmd:r(nfloorforced}{it:n}{cmd:)}}the number of accepted strata for propensity score {it:n} that were floor-forced rather than cleanly balanced{p_end}
{synopt:{cmd:r(nexcluded}{it:n}{cmd:)}}the number of regions excluded (missing a treatment level) for propensity score {it:n}{p_end}
{synopt:{cmd:r(exclobs}{it:n}{cmd:)}}the number of observations set to missing due to exclusion, for propensity score {it:n}{p_end}
{synopt:{cmd:r(smdlevel}{it:n}{cmd:)}}the {opt smdlevel()} threshold applied for propensity score {it:n}{p_end}
{synopt:{cmd:r(capped}{it:n}{cmd:)}}1 if the {opt smax()} ceiling on total strata was reached for propensity score {it:n}, 0 otherwise{p_end}

{synoptset 17 tabbed}{...}
{p2col 5 15 19 2: Matrices}{p_end}
{synopt:{cmd:r(smd)}}accepted strata for each propensity score (will have a suffix for each respective propensity score, e.g. {it:smd1}): stratum label, N,
maximum pairwise SMD, floor-forced flag, mean pairwise SMD, Cohen's f {p_end}
{synopt:{cmd:r(excl)}}excluded regions for each propensity score (will have a suffix for each respective propensity score, e.g. {it:excl1}): region label, N,
excluded flag {p_end}


{title:References}

{p 4 8 2}
Austin, P. C. 2009. Balance diagnostics for comparing the distribution of baseline covariates between treatment groups in propensity-score matched samples.
{it:Statistics in Medicine} 28: 3083{c -}3107.

{p 4 8 2}
Cochran, W. G. 1968. The effectiveness of adjustment by subclassification
in removing bias in observational studies.
{it:Biometrics} 24: 205{c -}213.

{p 4 8 2}
Linden, A. 2014. Combining propensity score-based stratification and weighting to improve
causal inference in the evaluation of health care interventions.
{it:Journal of Evaluation in Clinical Practice} 20: 1065{c -}1071.

{p 4 8 2}
Linden A. 2017. A comparison of approaches for stratifying on the propensity score to
reduce bias.
{it:Journal of Evaluation in Clinical Practice} 23:690{c -}696.

{p 4 8 2}
Linden, A. & Adams, J. L. 2008. Improving participant selection in
disease management programs: insights gained from propensity score
stratification.
{it:Journal of Evaluation in Clinical Practice} 14, 914{c -}918.

{p 4 8 2}
Linden, A., Uysal, S. D., Ryan, A., & Adams, J. L. 2016. Estimating causal effects for multivalued treatments:
A comparison of approaches.
{it:Statistics in Medicine} 35: 534{c -}552.

{p 4 8 2}
Rosenbaum, P. R. & Rubin, D. B. 1984. Reducing bias in observational
studies using subclassification on the propensity score.
{it:Journal of the American Statistical Association} 79, 516{c -}524.

{p 4 8 2}
Rubin, D. B. 2001. Using propensity scores to help design observational studies: application to the tobacco litigation.
{it:Health Services and Outcomes Research Methodology} 2: 169{c -}188.



{marker citation}{title:Citation of {cmd:pstrata}}

{p 4 8 2}{cmd:pstrata} is not an official Stata command. It is a free contribution
to the research community, like a paper. Please cite it as such: {p_end}

{p 4 8 2}
Linden, A. 2016. PSTRATA: Stata module for implementing optimal propensity score stratification. Statistical Software Components S458232, Boston College Department of Economics {p_end}



{title:Author}

{p 4 4 2}
Ariel Linden{break}
alinden@lindenconsulting.org



{title:Acknowledgments}

{p 4 4 2}
I wish to thank Nicholas J. Cox for his support while initially developing {cmd:pstrata}.{p_end}


{title:Also see}

{p 4 8 2}Online:  {helpb xtile}, {helpb logit}, {helpb mlogit}, {helpb margins}, {helpb marginsplot}, {helpb teffects},
 {helpb mmws} (if installed), {helpb covbal} (if installed) {p_end}
