{smcl}
{* *! version 1.0.0 20June2015}{...}

{title:Title}

{p2colset 5 17 21 2}{...}
{p2col:{hi:looclass} {hline 2}} Classification statistics for leave-one-out cross-validation of binary outcomes  {p_end}
{p2colreset}{...}


{marker syntax}{...}
{title:Syntax}


{p 8 17 2}
{cmd:looclass} {depvar} [{indepvars}] {ifin} [{it:{help weight}}]
[{cmd:,} {opt probit} {opt cut:off}{it:(#)} {opt fig:ure} {it:model_options} ]


{synoptset 19 tabbed}{...}
{synopthdr}
{synoptline}
{synopt:{opt probit:}}use probit regression for estimation; default is logit{p_end}
{synopt :{opt cut:off(#)}}positive outcome threshold used in classification tables; default is {cmd:cutoff(0.5)}{p_end}
{synopt:{opt fig:ure}}produces a graph presenting ROC curves for the training and test data{p_end}
{synopt:{it:model_options}}specifies all available options for {help probit} when the {cmd:probit} 
option is chosen; otherwise all available options of {help logit} {p_end}
{synoptline}
INCLUDE help fvvarlist
{marker weight}{...}
{p 4 6 2}{opt fweight}s, {opt iweight}s, and {opt pweight}s are allowed; see
{help weight}.{p_end}


{p 4 6 2}
{p2colreset}{...}				
	
{title:Description}

{pstd}
{cmd:looclass} performs leave-one-out cross-validation for regression models with a binary outcome and then produces classification measures to assist in determining 
the error rate (or conversely, the accuracy) of a prediction (classification) model. {p_end}  

{pstd}
Leave-one-out cross-validation is simply {it:n}-fold cross-validation, where {it:n} is the number of observations in the dataset. Each observation in turn is 
left out, and the logit (or probit) model is estimated for all remaining observations. The predicted value is then calculated for the one hold-out observation, 
and the accuracy is determined as success or failure in predicting the outcome for that observation (see Chapter 5 in Witten et al. 2011). The results of all {it:n} 
predictions are used to calculate the final error estimates (accuracy) displayed in the classification table and ROC curves generated by {cmd:looclass}. 
 

{title:Options}

{p 4 8 2}
{cmd:probit} specifies that probit regression should be used as the estimation model; default is {cmd:logit}.

{p 4 8 2}
{cmd:cutoff(}{it:#}{cmd:)} specifies the value for determining whether an observation has a predicted 
positive outcome in the classification tables.  An observation is classified as positive if its
predicted probability is {ul:>} {it:#}.  The default is 0.5.  
		
{p 4 8 2}
{cmd:figure} produces a graph presenting ROC curves for the training and test data.

{p 4 8 2}
{cmd:{it:model_options}} specifies all available options for {help probit} when the {cmd:probit} 
option is chosen; otherwise all available options of {help logit}.

	

{title:Examples}

{hline}

{pstd}Setup{p_end}
{phang2}{cmd:. webuse lbw}{p_end}

{pstd}
Leave-one-out cross validation using logistic regression and displaying the ROC curves  {p_end}
{phang2}{cmd:. looclass low age lwt i.race smoke ptl ht ui, fig}{p_end}

{pstd}
Same as above but specifying probit as the estimation model with robust standard errors  {p_end}
{phang2}{cmd:. looclass low age lwt i.race smoke ptl ht ui, fig probit vce(robust)}{p_end}

{pstd}
Same as above but limiting age to less than 28  {p_end}
{phang2}{cmd:. looclass low age lwt i.race smoke ptl ht ui if age <28, fig probit vce(robust)}{p_end}
{hline}

{title:Stored results}

{pstd}
{cmd:looclass} stores the following in {cmd:r()}:

{synoptset 15 tabbed}{...}
{p2col 5 15 19 2: Scalars}{p_end}
{synopt:{cmd:r(P_corr_1)}}percent correctly classified - training{p_end}
{synopt:{cmd:r(P_p1_1)}}sensitivity - training{p_end}
{synopt:{cmd:r(P_n0_1)}}specificity - training{p_end}
{synopt:{cmd:r(P_p0_1)}}false-positive rate given true negative - training{p_end}
{synopt:{cmd:r(P_n1_1)}}false-negative rate given true positive - training{p_end}
{synopt:{cmd:r(P_1p_1)}}positive predictive value - training{p_end}
{synopt:{cmd:r(P_0n_1)}}negative predictive value - training{p_end}
{synopt:{cmd:r(P_0p_1)}}false-positive rate given classified positive - training{p_end}
{synopt:{cmd:r(P_1n_1)}}false-negative rate given classified negative - training{p_end}
{synopt:{cmd:r(roc1)}}ROC curve - training{p_end}
{synopt:{cmd:r(P_corr_2)}}percent correctly classified - test{p_end}
{synopt:{cmd:r(P_p1_2)}}sensitivity - test{p_end}
{synopt:{cmd:r(P_n0_2)}}specificity - test{p_end}
{synopt:{cmd:r(P_p0_2)}}false-positive rate given true negative - test{p_end}
{synopt:{cmd:r(P_n1_2)}}false-negative rate given true positive - test{p_end}
{synopt:{cmd:r(P_1p_2)}}positive predictive value - test{p_end}
{synopt:{cmd:r(P_0n_2)}}negative predictive value - test{p_end}
{synopt:{cmd:r(P_0p_2)}}false-positive rate given classified positive - test{p_end}
{synopt:{cmd:r(P_1n_2)}}false-negative rate given classified negative - test{p_end}
{synopt:{cmd:r(roc2)}}ROC curve - test{p_end}
{p2colreset}{...}


{title:References}

{p 4 8 2}
Witten, I. H., E. Frank, and M. A. Hall. (2011) {it:Data Mining: Practical Machine Learning Tools and Techniques (3 ed.)}. Boston: Elsevier Press. {p_end}

{p 4 8 2}
Linden A. (2006) Measuring diagnostic and predictive accuracy in disease management: an introduction to receiver operating characteristic (ROC) analysis. 
{it:Journal of Evaluation in Clinical Practice} 12: 132-139.{p_end}



{marker citation}{title:Citation of {cmd:looclass}}

{p 4 8 2}{cmd:looclass} is not an official Stata command. It is a free contribution
to the research community, like a paper. Please cite it as such: {p_end}

{p 4 8 2}
Linden, Ariel (2015). looclass: Stata module for generating classification statistics of Leave-One-Out cross-validation for binary outcomes{p_end}


{title:Author}

{p 4 8 2}	Ariel Linden{p_end}
{p 4 8 2}	President, Linden Consulting Group, LLC{p_end}
{p 4 8 2}	Ann Arbor, MI, USA{p_end}
{p 4 8 2}{browse "mailto:alinden@lindenconsulting.org":alinden@lindenconsulting.org}{p_end}
{p 4 8 2}{browse "http://www.lindenconsulting.org"}{p_end}

         

{title:Also see}

{p 4 8 2} Online: {helpb probit}, {helpb logit}, {helpb estat classification}, {helpb roccomp}, {helpb loocv} (if installed), {helpb crossfold} (if installed){p_end}

