# This is a basic workflow that is manually triggered

name: Mirror workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      suffix:
        description: "Suffix to be added to tag"
        required: true
        default: ''
  schedule:
    - cron: "42 3 * * *"
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Set environment vars
      run: echo "PULLDATE=$(date +%F)" >> $GITHUB_ENV
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        path: bin
    - name: Checkout last mirror
      uses: actions/checkout@v2
      with:
        ref: releases
        path: mirror
    - name: Mirror archive data
      run: |
         chmod +x bin/mirror.repec.sh
         cd mirror/
         ../bin/mirror.repec.sh
   # Deploy to a new branch      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: mirror
        publish_branch: releases
        keep_files: true
        full_commit_message: "Snapshot of SSC Archive as of ${{ env.PULLDATE }})"
        tag_name: ${{ env.PULLDATE }}${{ github.event.inputs.suffix }}"
        tag_message: "Snapshot of SSC Archive as of ${{ env.PULLDATE }}${{ github.event.inputs.tags }})"
